include/client.h, include/http_defs.h, include/router.h, src/client/client.cc, src/server/router.cc
These two commits add PATCH to the router and client.
=> Add PATCH method

include/description.h, include/http.h, src/common/http.cc, src/server/listener.cc
Those are some minor bugfixes.
=> added missing returns, listener check if bound on deconstruct

include/router.h, src/server/router.cc
This adds Options Method to the Router
=> adding OPTIONS method to router

include/pistache/http_defs.h
This also close #127  
source https://httpstatuses.com/
=> Add more to Http::Code

include/pistache/stream.h, src/client/client.cc
=> Avoid overflow when buff exactly full

CMakeLists.txt, include/pistache/async.h, include/pistache/common.h, include/pistache/cookie.h, include/pistache/description.h, include/pistache/flags.h, include/pistache/http.h, include/pistache/iterator_adapter.h, include/pistache/mailbox.h, include/pistache/optional.h, include/pistache/os.h, include/pistache/reactor.h, include/pistache/router.h, include/pistache/stream.h, include/pistache/transport.h, include/pistache/version.h.in, libpistache.pc.in
Fixes a plethora of compiler warnings. This includes the pkg-config / versioning fixes as well because I couldn't figure out how to remove them from this branch.
=> Fix warnings

src/client/client.cc
Otherwise std::bad_function thrown
Fixes #117
=> Check inflightRequests not empty to grab el; and check onDone non-null to call

src/client/client.cc
In this PR I have done tiny change in processRequestQueue to make code better
=> Tiny change in processRequestQueue to make code better

include/pistache/client.h, include/pistache/router.h, src/client/client.cc, src/server/router.cc
In this pull request I have improved `std::string` usage in code
=> Improve string usage in code

src/client/client.cc
In this PR I'm adding the implemetation of method for setting timeout in RequestBuilder
=> Implement set timeout method in RequestBuilder

include/pistache/http.h, include/pistache/http_defs.h, src/client/client.cc, src/common/http_header.cc
I this PR I have made small refactoring in code
=> Refactoring and getting rid of magic number

include/pistache/http.h, src/client/client.cc, src/common/http.cc, src/common/stream.cc
I this PR I have made several tiny code improvements
=> Tiny code improvements

src/common/description.cc
=> Fixed potential empty path in Swagger description

include/pistache/cookie.h, tests/cookie_test_2.cc
Also added additional unit test to verify operators: pre-increment, post-increment, '*', '->'.
=> Pre-increment should return reference, not value.

src/client/client.cc, src/common/transport.cc
In this PR I have made several code improvements
=> Several code improvements

examples/custom_header.cc, include/pistache/http_header.h, include/pistache/http_headers.h, src/common/http_headers.cc, tests/headers_test.cc
In this PR I'm fixing a lot of override warning and adding Headers registry test
=> Fix warnings in headers and add registry test

CMakeLists.txt, examples/CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
Issue #357 > Add Target  pistache_shared, pistache_static
Update GCC Version Check and CXX_STANDARD Setting
=> Change Cmakefiles > Issue #357 

include/pistache/client.h, src/client/client.cc
I this PR I'm improving lambda captues and deleting unused code
=> Code improvements: lambdas and tiny changes

src/common/http_header.cc, tests/headers_test.cc
Hello
I was using Date::write. So I contributed implementing it. Maybe all methods that aren't implemented should emit a warning.
Arthur
=> Implementation of Date::write

include/pistache/stream.h, include/pistache/transport.h, src/common/transport.cc
https://github.com/oktal/pistache/issues/399#issuecomment-459224155
=> Fix buffer memory leak

tests/headers_test.cc
The target of this branch is 100% coverage over http_headers.cc. So don't merge it now.
=> Added test cases to exceptions and some uncovered methods in headers

tests/streaming_test.cc
Use trivial Thread pool instread of creating plenty of threads that can hit limits
=> Fix issue #473: threads problem

include/pistache/config.h, include/pistache/http_defs.h, include/pistache/net.h, src/common/http_header.cc, src/common/net.cc, tests/net_test.cc
Now you can execute the following command:
```
$ ./examples/run_http_client www.example.com
```
=> Partially fix issue #420

src/client/client.cc, tests/http_client_test.cc
=> added query to path string

CMakeLists.txt
=> Change version.h and libpistache.pc install source location to use CMAKE_CURRENT_BINARY_DIR

include/pistache/optional.h, tests/CMakeLists.txt, tests/optional_test.cc
=> Fix optional

tests/optional_test.cc
Some improvements and a fix to recently submitted #589 by @muttleyxd (please have a look).
=> changes of ut optional

include/pistache/http.h, src/common/http.cc, tests/http_server_test.cc
For issue #239, this copies the Address from the requesting Peer into the Request.
=> adds address copying to request, and test

include/pistache/router.h, src/server/router.cc, tests/router_test.cc
Adding router to support HTTP HEAD method request.
=> Add support router HEAD request

README.md
The package only compiled in >= C++14.
=> Update C++ version

CMakeLists.txt, include/pistache/optional.h, src/common/description.cc, src/common/http.cc, src/common/http_headers.cc, src/common/mime.cc, tests/optional_test.cc
Had to hack around apparent bug in cppcheck. :(
=> Elminiated the cppcheck findings for include/pistache/optional.h.

src/common/description.cc
Current count of PRs out for review is low; and we'll likely cancel several of them anyway.
The existing code is inconsistently formatted.  This seems like a good time as any to establish a consistent format, then add a pre-submit check that all new code is formatted.  I'm creating the single-file PR so that the yak-shaving can commence.
=> Reformatted with 'clang-format' with default options.

include/pistache/client.h, include/pistache/http.h, src/client/client.cc, src/common/http.cc
I have made changes in the codebase following my description in #673 . I haven't added new unit tests consciously, because in this refactoring I didn't add new API or change the behaviour of any classes. Just changes in code structure and current tests cases can check my changes.
=> Issue #673: refactoring

include/pistache/async.h, include/pistache/http_defs.h, include/pistache/mailbox.h, include/pistache/router.h, include/pistache/stream.h
Added override keyword to reduce compiler warnings (C++11, -Wsuggest-override).
=> Add override keyword to functions who override

.travis.yml
Trying to fix issue #720 and follow example [here](https://github.com/springmeyer/travis-coredump/blob/master/.travis.yml).
=> Issue #720: Add ulimit -c unlimited -S to CI

src/common/net.cc, tests/http_server_test.cc
1) In these changes I'm trying to improve code in `Address::init` and remove redundant executions;
2) More logs to `http_server_test`.
=> Code improvements in Address class and more logs

src/common/http_header.cc
I have fixed one warning from #681 and made small improvement in code
=> Fix issue #681 and small improvement

examples/rest_server.cc, include/pistache/description.h, src/server/router.cc
I have found several places that can be improved with small fixes
=> Several minor fixes in router code

examples/http_client.cc
Changing `http_client` examples following questions in #745
=> Issue #745: changes in http_client example

include/pistache/router.h, src/server/router.cc, tests/router_test.cc
This commit partially resolves #24, which is a common requirement on
many RESTful services.
A vector of middleware handlers is added to Router, these handlers are
executed before the URL match and handler invocation, in the order of
registration.
A middleware function has the signature:
bool func(Pistache::Http::Request &request,
Pistache::Http::ResponseWriter &response);
The first parameter is a reference to Http::Request, not Rest::Request,
at the moment middlewares are called, the request parameters are not yet
filled. This allows some generic operation on the request, such as
authentication or rate limiting.
Parameters are passed as references, to allow the middlewares be able to
modify them, such as injecting custom headers.
If a function returns true, the next function is executed, …
=> Add middleware support

tests/router_test.cc
1) Added test for `sanitizeResource` static function
2) Fixed warnings (used variables)
3) Small improvements in constructors
=> Add test for sanitize resource + small improvements

include/pistache/net.h, src/common/net.cc
1) It's better to use `::getaddrinfo` instead of `::gethostbyname`
2) Start refactoring in `Address` class
=> Change using ::gethostbyname to AddrInfo + start Address class refactoring

tests/streaming_test.cc
In my opinion it is not the best choice to use delays to test stream of data between client and server. I have decided to use chunks to store the date and check these chunks afterwards.
=> Fix issue #803: redesign ChunkedStream test

include/pistache/http.h, include/pistache/peer.h, src/common/http.cc, src/common/peer.cc, tests/http_server_test.cc
Reverts pistacheio/pistache#836
Broke the build.
=> Revert "Adding a Peer ID to identify connections"

CMakeLists.txt
=> Remove -fprofile-arcs that causes build failure

include/pistache/router.h, src/common/http.cc, src/server/router.cc
I have found several places in code with unnecessary copies of objects and fixing them in this PR.
=> Fix several unnecessary copies of objects

README.md
=> Fix CMake pkg-config example

include/pistache/net.h, src/client/client.cc, src/common/net.cc, src/common/peer.cc, tests/http_server_test.cc
More traces for issue #842 investigation
=> #842: Add more debug traces to http server test

.travis.yml, CMakeModules/CheckAtomic.cmake, README.md, debian/control, debian/rules, examples/meson.build, include/pistache/meson.build, libpistache.pc.in, meson.build, src/meson.build, tests/meson.build
Reverts pistacheio/pistache#890
=> Revert "Meson improvements"

README.md
=> Add project status in the Readme

.travis.yml
`AllowShortBlocksOnASingleLine: Empty` was added in clang-format 10
=> Update clang-format in Travis

.clang-format, examples/custom_header.cc, examples/hello_server.cc, examples/http_server.cc, examples/http_server_shutdown.cc, examples/rest_server.cc, include/pistache/async.h, include/pistache/http_header.h, include/pistache/prototype.h, include/pistache/reactor.h, include/pistache/router.h, src/client/client.cc, src/common/http_header.cc, src/common/reactor.cc, src/common/transport.cc, src/server/listener.cc, tests/async_test.cc, tests/cookie_test_2.cc, tests/headers_test.cc, tests/https_server_test.cc, tests/listener_test.cc, tests/router_test.cc, tests/streaming_test.cc
As always, I fogot about something
=> Complete #933

include/pistache/meson.build
=> Fix serializer install and remove unneeded prefix

.github/workflows/autopkgtest.yaml
=> ci(autopkgtest): drop uscan, use manual .orig tarball

tests/meson.build
It got fixed in f3287312521d8348da4b62af68f39787c8829d73
=> build(test): mark streaming_test as not flaky

pistache.io/docs/http-handler.md
It's only a simple fix, but my first pr. Hope everything is fine.
=> docs: fix static file serve example

.github/workflows/debian-changelog.yaml
These should be the last fixes needed to make this work. It does work now in my fork, see <https://github.com/Tachi107/pistache/actions/runs/4217592497/jobs/7321484202>
=> ci(debian-changelog): last fixes

.github/workflows/abidiff.yaml, .github/workflows/reuse.yaml, .hooks/pre-commit
Small updates unrelated to macOS support split out of #1197
Cc: @dgreatwood, @kiplingw
=> Small updates from #1197

.reuse/dep5, LICENSES/MIT.txt, subprojects/cpp-httplib/httplib.h, subprojects/cpp-httplib/meson.build, subprojects/gtest.wrap, subprojects/rapidjson.wrap
This PR updates the cpp-httplib, Google Test and rapidjson subprojects. Hopefully fixes some of the issues mentioned in https://github.com/pistacheio/pistache/pull/1197#issuecomment-2143205975
=> build: update subprojects

control
Needed for https://github.com/pistacheio/pistache/pull/1197
=> control: build-depend on libevent-dev

.github/dependabot.yml, .github/workflows/linux.yaml
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)
=> ci: Keep GitHub Actions up to date with GitHub's Dependabot
