pistacheio/pistache

include/http_header.h
src/common/reactor.cc

This pull fixes 3 issues reported by valgrind.
**UMR issue:** Two variables were being used to loop but were not initialized in constructor) added them.
**Major memory leak:** The HttpHeaders destructor was not virtual leading to memory leak in Net::Http::Header::Accept::parseRaw which add MimeType objects to a vector. This would leak ~150 bytes every single request. I ran about 400K requests (Hello world) and it already leaked 74MB+ memory. This would make the framework completely unusable.
I request you to kindly run valgrind on your programs to detect these kinds of issues.

[IMPORTANT] Memory related fixes

---

tests/async_test.cc

Hi, had problems compiling tests.
Here's small hotfix.
General worflow:
```
git clone ...
mkdir build && cd build
cmake ../pistache
make
```
```
[ 86%] Linking CXX executable hello_server
/home/misty_fungus/workspace/pistache/tests/async_test.cc:382:10: error: ‘random_device’ in namespace ‘std’ does not name a type
std::random_device rd;
^~~~~~~~~~~~~
[ 86%] Built target hello_server
```

Fix async_test.cc compilation

---

src/common/os.cc

@michalpelka hit an issue ( #29 ) where attaching gdb and stepping
through code fails with a `terminate called after throwing an instance of
'Net::Error' what(): Polling: Interrupted system call`.  @michalpelka then
identified the fix which involves continuing to call `epoll` in the event
of an interrupt
After build `make test` passed and I can confirm that the fix enables the 
use of `gdb` and `gdbtui`.

Enables gdb debugging by fixing the polling code to allow interrupts.

---

src/common/net.cc

It does not convert from network byte order to host byte order for the port field of the struct sockaddr_in.
This is easily solved by using ntohs
IMHO, you should also rename this. fromUnix suggests that it is expecting a sockaddr_un (an address for a unix domain socket), not a sockaddr_in.

Address::fromUnix gets the port wrong

---

src/server/endpoint.cc
src/server/router.cc

I assume Endpoint::bind() is supposed to be a wrapper for the bind() method of the underlying listener.

Fix missing bind() and wrong comment

---

CMakeLists.txt

In commit 76db321 when rapidjson dependency was removed, `/include/serializer/rapidjson.h` was introduced. However, the CMakeLists.txt was not adjusted to consider subdirectories of `/include` for installation. Therefore, projects modelled based on `/examples/rest_description.cc` fail to compile because `#include "serializer/rapidjson.h"` does not work.
This fixes the error by including `/include/serializer` in the CMake installation script.

Include serializer code in CMake install script

---

README.md

Appearantly the HTTP_PROTOTYPE macro is needed, otherwise the example
won't compile.
The compile error was:
```
/usr/local/include/pistache/http.h:758:5: error: static assertion failed: An http handler must be an http prototype, did you forget the HTTP_PROTOTYPE macro ?
static_assert(details::IsHttpPrototype<H>::value, "An http handler must be an http prototype, did you forget the HTTP_PROTOTYPE macro ?");
```
The fix was also mentioned in #71 but it seems the README didn't actually get updated.

README: fix hello world example so it compiles

---

include/mime.h

Now MIME3 can be used in an expression just like MIME can.

Fix bad extra semicolon in MIME3 macro

---

include/async.h

Warnings reported by Visual Studio. Nothing serious, but still, less warnings - better.

Fix class\struct inconsistency warnings

---

CMakeLists.txt
src/CMakeLists.txt
src/PistacheConfig.cmake.in

This PR contains 2 patches I created for Arch Linux packaging.
The first patch renames the library to `pistache` to avoid a conflict with libnet (https://www.archlinux.org/packages/extra/x86_64/libnet). I understand if you don't like renaming the targets because all projects using it would need to adopt. Note that libnet is more popular and there already packages for different distributions (https://repology.org/metapackage/libnet/versions).
The second patch builds currently on top of the first one. It adds CMake config files so the library can be used more easily from other CMake projects. Using the lib via such a config is better because it preserves link libs, compile definitions and other target properties.
BTW: For the package see https://aur.archlinux.org/packages/pistache-git / …

Patches for Arch Linux packaging

---

include/pistache/stream.h
include/pistache/transport.h
src/common/transport.cc

Added offset_ to BufferHolder so that retries would remember where they left off,
Fixed range of copying in struct Buffer so that large dynamic responses still work.

Fixed the inability to serve static files greater than 140 KB

---

include/pistache/mime.h

Just add function for cmp MediaTypes to avoid  `!((MediaType)m1 == (MediaType)m2)`

Add operator!= for MediaType

---

include/pistache/http_defs.h

Hi,
The function ```versionString()``` is defined at ```http_defs.cc``` but is not available for use through the ```http_defs.h``` header file. 
My personal use case with ```versionString()``` is for logging purpose.
Regards.

Add versionString function at http_defs.h header file

---

README.md

This is a simple update to the README.md to include build info plus notes for building the examples. Most of the notes are from the Getting Started document, but having it in the README.md makes it easier to find.

Simple update to the README.md to include build info 

---

README.md

make test will not work without first enabling the build of the tests.
The README.md documentation was not updated when the change that
requires the variable be enabled (863eba92) was pushed.
This resolves part of Issue #249 in that with it in place and clean
working directory the tests will compile and run.
It is probably not enough to consider #249 complete at present as all of
the test fail on my system, suggesting something is grossly wrong.

Add cmake Setup Instructions For make test

---

README.md

Not everyone wants to join a private channel on Slack.  The current maintainer and a few active contributors vastly prefer IRC, so I updated the documentation to list both contact methods.

Updating contact info in README.txt

---

include/pistache/http.h

Fix for this issue: https://github.com/oktal/pistache/issues/222
Allows distinguishing between different active connections more easily.

ResponseWriter's peer() method is now public

---

.travis.yml
include/pistache/date.h
include/pistache/http_defs.h
include/pistache/http_header.h
src/CMakeLists.txt
src/common/cookie.cc
src/common/http_defs.cc
src/common/http_header.cc
tests/cookie_test.cc
tests/headers_test.cc

Hi,
Here is my proposal of changing `std::tm` to `std::chrono::time_point` And include "date.h" [dock here](https://howardhinnant.github.io/date/date.html) and presentation at [cppcon](https://www.youtube.com/watch?v=tzyGjOm8AKo)
Plus:
- more c++11
- more portable
- is smaller (8 bytes) std::tm (52 bytes)
- compiler catch errors
Minus:
- slower (avg: ~1.731 us (date.h) to ~0.820 us (std::tm) for RFC1123 parsing)
This is better (in my opinion) solution for #131.

Change std::tm to time_point and add "date.h"

---

include/pistache/mime.h
src/common/http.cc
src/common/mime.cc

Start here https://github.com/oktal/pistache/blob/b66415aaa0dc443b7874acbbb488058b34c2dc01/src/common/http.cc#L710 :
```
auto mime = Mime::MediaType::fromFile(fileName);
if (mime.isValid())
setContentType(mime);
```
If we don't know what this file is we can always use application/octet-stream?!

Add application/octet-stream to be type-safe

---

include/pistache/http.h
src/common/http.cc

The query is only defined for Server purpose. I added ~`str()`~ `as_str()` method that generate part of url.
U can now create a own Clinet Wraper for some API with easy query parametes (they can by create from initialization list).
If sb has idea how make them compile-time safe in client form don't hesitate.

Query in client

---

include/pistache/client.h
src/client/client.cc

In this pull request I propose to use `shared_ptr` instead of raw pointer to manage `Connection::RequestData` in `requestsQueues`. As a result you don't need to delete resource manually and worry about cleaning memory in case of expection.

Improve memory management using shared_ptr instead of raw pointer

---

include/pistache/client.h
src/client/client.cc

In this PR I'm fixing redundant strings copying in `Client` class. It would be better to pass resource name by `const std::string&` instread of creating a lot of template object during chain of calls. You can do perfomance tests with passing plenty of strings to `get` method and see the result.

Fix perfomance issue: redundant strings copying

---

examples/http_server.cc
include/pistache/http.h

Adds a `ResponseStream::write(char *, std::streamsize)` method, which is helpful for sending chunked binary data (e.g. large gzip'd responses).
Also adds a `/stream_binary` example path to the run_http_server to show the write() call in action.

Stream write

---

src/common/reactor.cc

Hello,
I tried to compile the project with C++17 and clang 6.0. I got an include error. I fixed. Please merge.
Br:
Antal Tatrai

fix building on clang 6.0

---

include/pistache/common.h
include/pistache/http_header.h
src/common/http_header.cc
src/common/http_headers.cc
tests/headers_test.cc

Added Access-Control-Allow-Headers to the set of headers.
This is needed when calling endpoint from JavaScript in a browser, otherwise we run into an error in the OPTIONS request.

Added Access-Control-Allow-Headers to the set of headers

---

include/pistache/net.h
src/client/client.cc
src/common/net.cc
src/server/listener.cc
tests/net_test.cc

In this PR I have moved port value convertion to `std::string` to `Port` class and implemented tests. Also I have moved `*` to `0.0.0.0` convertion to `Address::init`.

Code refactoring: move port value convertion to string to Port class

---

include/pistache/http_headers.h

It may happen that the headers are not know in advance. One possible
scenario is that the caller provide a bunch of arbitrary headers with a
predefined prefix, acting as customer metadata, that the applications
needs to store somewhere for later reuse, in responses for example.
Those arbitrary might be used by the customer for many purposes, like
custom load-balancing or particular routing.

Allow access to unknown and arbitrary raw headers

---

tests/listener_test.cc

If the listener::init, call is not present, the listener object will be in a state where its workers_ member is not initialized (size_t). In clang, this leads to the creation of an absurd number of threads which in turn
will make eventfd call fails in NotifyFd. See issue 302 for more details.

Issue 302 - Fix listener_test

---

include/pistache/common.h
include/pistache/listener.h
src/server/listener.cc
tests/listener_test.cc

2 changes here:
- The first one is to initialize explicitly the members of Listener. This is to fix the problem that happens when Listener::init is not called before running (see issue 302).
- Replace shared_ptr<Aio::Reactor> by a value owned by Listener. The pointer was never shared with anything else so it makes sense to use a value instead of a shared_ptr for this case.
Please do not merge yet -> Will add a UT where listener is not init, but does not crash.

Initialize members of Listener with default value - Remove shared pointer 

---

include/pistache/listener.h
src/server/listener.cc

In this PR I propose tiny changes in `Listener` implementation:
1. Before calling `join` for thead it would be better to check that it's joinable;
2. In my opinion using `std::unique_ptr` is redundant in this case.

Tiny change in thread management

---

include/pistache/endpoint.h
include/pistache/listener.h
src/server/listener.cc

In this PR have added using 'std::make_shared' instead of reset call (why it's better you can read [here](https://stackoverflow.com/questions/14836691/is-it-better-to-use-shared-ptr-reset-or-operator)). Also I have changed return value of `Listener::bind` methond because returning `bool` value looks obsolete.

Code improvements

---

src/server/endpoint.cc
tests/http_client_test.cc

This is the first part of changes for fixing http client test. We definitelly should create server with `Tcp::Options::ReuseAddr` option. Now I'm researching the roots of the following problem:
```
10: [ RUN      ] request_builder.multiple_send_test
10: terminate called after throwing an instance of 'Pistache::Http::HttpError'
10:   what():  Encountered invalid HTTP version
1/1 Test #10: http_client_test .................***Exception: Child aborted  0.50 sec
```
This problem was raised after my [commit](https://github.com/oktal/pistache/commit/11bba3e994d33f1e9b476b15a2f8f3e8c3d1bd65) when I added http client test for checking multiple send method calls.

Add address reuse in http client test

---

src/common/transport.cc
tests/http_client_test.cc

In this PR I have partially reverted [4b18505](https://github.com/oktal/pistache/commit/4b185059fbae6c96f330dbf5550f38f38d82a861) that breaks `http_client_test` and added more tests. I will continue explore how Transport works and propose better solution but for this moment it's just partially revert to fix test.

Test fix: partially revert 4b18505 that breaks http_client_test + add more tests

---

include/pistache/common.h

In this PR I'm proposing adding printing file name and line number in `TRY` and `TRY_RET` macroses to improve debugging info. For instance, now It helps me to exploring  
`epoll_ctl(epoll_fd, EPOLL_CTL_MOD, fd, &ev): Bad file descriptor` problem. In the future we can add turning on/off printing this info on debug flag.

Add printing file name and line number in TRY and TRY_RET 

---

CMakeLists.txt

Resolve the problem shown by @janhkrueger in #306 by lowering the CMAKE required version and using a manual check on C++17 support for versions lower than 3.8

Relaxed CMAKE version requirement

---

include/pistache/string_view.h
tests/string_view_test.cc

Cleaned up compiler warnings (comparison between signed and unsigned, ignored 'const'.

Reduced compiler warnings in string_view

---

src/common/transport.cc

In this PR I'm fixing two cases of heap usage after free:
1) We access `buffer` after deleting (in `cleanUp`) entry `wq.pop_front();` that contains it
2) We call `wq.size()` after deleting this queue (in `cleanUp`) using `toWrite.erase(fd);` call.
I will think about refactoring in this part of code.

Fix two heap usage after free

---

include/pistache/errors.h
src/server/listener.cc
tests/http_server_test.cc

In this PR I'm proposing inprovement of `accept` call on listening socket. In my opinition not all accept errors should cause server shutdown.

Improve error handling on accept call

---

.travis.yml
tests/http_server_test.cc

In this PR I have fixed problems in `http_server_test` related to timeouts. When I was writting this test I didn't take into account load balancing and dependency on file descriptor number here:
```
...
Listener::dispatchPeer(const std::shared_ptr<Peer>& peer) {
auto handlers = reactor_.handlers(transportKey);
auto idx = peer->fd() % handlers.size();
auto transport = std::static_pointer_cast<Transport>(handlers[idx]);
transport->handleNewPeer(peer);
}
...
```
That's why my tests could fail from time to time when request without delay waits transport of request with delay.

Fix problems in http_server_test and test refactoring

---

include/pistache/http.h
include/pistache/stream.h
src/common/description.cc
src/common/http.cc
src/common/stream.cc

In this PR I'm fixing issue #346 
File cannot be opened when we pass `const char *` of local `std::string` (using `c_str()` call) to `serveFile`. By the time of calling `FileBuffer::init` the local variable of type `std::string` is deleted and location of memory to `fileName` (that we got by `c_str()` call) contains garbage.

Fix issue #346

---

include/pistache/string_view.h
tests/string_view_test.cc

In this PR I have made changes in `string_view` `find` and `rfind` methods to make them really `noexpect`. Now `substr` call can throw exception in the current version of this method.

Make string_view find and rfind methods really noexcept

---

include/pistache/client.h
src/client/client.cc
tests/cookie_test_3.cc

In this PR I have made the following things that make the code better (from my point of view):
1) Replace `Buffer` to `std::string`. I think it would be better to use STL containers in **this case** instead of implementing your own.
2) Replace `DynamicStreamBuf` to `std::stringstream` and checking this stream in one place;
3) Remove from client explicit `delete[]` call. In modern C++ it would be better to avoid using raw pointers, explicit `new `and `delete` calls.
3) Fix several warnings

Client code refactoring

---

include/pistache/async.h
include/pistache/client.h
src/client/client.cc
tests/http_client_test.cc

In this PR I'm fixing the problem in `Connection` class. It can happen that (not so often, but tests show some flaky situations):
```
...
transport_->asyncSendRequest(shared_from_this(), timer, std::move(buffer)).then(
[=](ssize_t) mutable {
inflightRequests.push_back(RequestEntry(std::move(resolveMover), std::move(rejectMover), std::move(timer), std::move(onDone)));
},
...
```
is executed **after**:
```
...
void
Connection::handleResponsePacket(const char* buffer, size_t totalBytes) {
parser_.feed(buffer, totalBytes);
if (parser_.parse() == Private::State::Done) {
if (!inflightRequests.empty()) {
...
```
and as a result we **miss response** to client because `inflightRequests` is empty. I have analyzed Client logic and understood that inflightRequests size **can not be more than one**. …

Fix Connection problem in Client + code refactoring + one more test

---

include/pistache/async.h
src/client/client.cc

In the previous PR I have made the `EmptyCall` functor very specific (`operator()(size_t)`) and in my opinion I was wrong. Let's revert this change.

Remove EmptyCall

---

include/pistache/client.h
src/client/client.cc
tests/http_client_test.cc

In this PR I'm fixing the problem with Connection that I have introduced in PR #374: when `maxConnectionsPerHost` is less than the number of requests for client.
The order of releasing `requestEntry` and calling `onDone` matter. I have added a test for reproducing this case. Also I have returned `Http::Response` parser to `Connection` level.

Fix connection OnDone execution: problem was introduced in PR #374 + test

---

include/pistache/http_header.h

Fixes several warnings issued by clang++

Add missing override to derived class virtual member functions

---

src/server/listener.cc

I noticed that when I call `endpoint->shutdown()`, the running `endpoint->serve()` never returns. After inspecting the code I saw that this is already being handled properly for `endpoint->serveThreaded()`, but not for `endpoint->serve()`.
This PR moves the necessary code from the `serveThreaded()` method to the `serve()` method, so both methods can be shutdown properly.
This is working great in my very quick test, but if this line was never added to the `serve()` method on purpose I would like to know why, so I can think of another solution.

Properly shutdown non-threaded serve

---

src/common/net.cc

Noticed a build warning while building the most recent `master` branch:
Tried to get through the quickstart guide and the application kept getting the `buffer overflow error`.
Upon further look at the culprit, there seems to be a copy/paste caused bug.
This single change removes the warning at compile time and fixes the bug.

Buffer overflow bug

---

include/pistache/client.h
src/client/client.cc

In this PR I'm fixing a problem that can happen when we establish connection (`transport_->asyncConnect(...)`), call `Connection::processRequestQueue`, but `requestsQueue.push(RequestData(...))` call takes place after that. As a result we can lose at least one request in client. To solve this problem I put reqeust to queue (in cases when we don't have connection) and only after that call `conn->connect(helpers::httpAddr(s.first));`.

Fix client send request problem (caused by connect and pop from queue order)

---

src/client/client.cc

See issue #392.
Essentially if the address is specified as either an IPv4 or IPv6 address then it uses the appropriate address family, if however it is a hostname (rather than an IP address) then it assumes IPv4.
In my eyes this patch is not the ideal solution as it doesn't implement Happy Eyeballs correctly, however it does fix the library such that all tests operate as expected without breaching the expectations of any users of the client portion of the library.
As such I propose we roll this patch until we have time to properly re-work the client side to include native dual-stack support.

Simple patch to bugs listed in #392

---

include/pistache/listener.h
include/pistache/net.h
src/common/net.cc
src/server/listener.cc
tests/listener_test.cc

Minor code refactor, no logic changes.  Move static utility function for checking ipv6 support from server class (Listener) to common class (Net), to make it cleaner to use from client.

Ipv6 support

---

include/pistache/net.h
src/server/listener.cc

Listener::bind() calls "getaddrinfo()", which allocates memory on the heap.  Later, Listenter::bind() has an exit path that fails to call "freeaddrinfo()".  I solved this by wrapping the "addr info" in a class that frees the addrinfo on destruction and provides read-only access to the same during its lifetime.
Addresses one memory leak from issue #399.

Fixes memory leak in Listenter::bind()

---

tests/net_test.cc
tests/payload_test.cc
tests/rest_server_test.cc
tests/streaming_test.cc

Converted final unit tests to use ephemeral ports.
Verified that no test binds TCP ports between 9080 and 9099 using "strace -ff -o tmp/x make test; egrep connect tmp/x.*"

Ephemeral port unit tests

---

include/pistache/client.h
src/client/client.cc
tests/http_client_test.cc

In this PR I'm fixing data races problem that can happen in `~Client` call (during Client destruction). Method `processRequestQueue` is called in async way so during `requestsQueues` `unordered_map` destruction in `~Client` it can be read in `processRequestQueue`. I have fixed this problem by introducing new flag `stopProcessPequestsQueues` that can prevent reading `requestsQueues` in `processRequestQueue` after `shutdown` call. Also I have added one more http client test (in the near future I will reduce code duplication in tests).

Fix data races in Client desctruction

---

include/pistache/client.h
src/client/client.cc

This is the first step of fixing memory leaks in `Client`. I just started from `ConnectionEntry` struct. In my opinion it should be used `std::weak_ptr` to hold connection to break cyclic references.

First step of fixing memory leaks in Client

---

include/pistache/http_header.h
src/common/mime.cc
src/server/router.cc
tests/headers_test.cc

This PR creates a Macro `CUSTOM_HEADER` for very simple HTTP Headers.
This has the benefit of still preserving the type safety of the library design as well as providing a quick and easy way to add custom headers without the hassle of writing the whole class structure.
I thought this PR is appropriate since I have seen many of this simplifications across the library like the function `Pistache::Http::listenAndServe` which improves the empty editor to hello world time.
I would recommend to review each commit on its own since the small changes may pollute a bit the editor. If you think the small changes should not be there by any reason please let me know and I can take them out.

Macro for simple HTTP headers

---

src/server/router.cc

GCC pre 4.9 has issue with template arg deduction which means old call passing char[2] to std::regex_replace as replacement string fails to build.

Work around regex_replace issue in GCC<4.9

---

examples/custom_header.cc
include/pistache/mailbox.h
include/pistache/peer.h
src/client/client.cc
src/common/http.cc
src/common/peer.cc
src/common/transport.cc
tests/https_server_test.cc

Fixing leaks in: https://github.com/oktal/pistache/issues/399
Mainly 2 issues:
1. mailbox.h leaking shared_ptr
Queue::Entry does not have a destructor. Anything put in "storage" will not be destroyed.
Queue::Entry stores std_shared_ptr in 'storage', so, the ref count never goes down.
Due to this, items extracted via: "Queue::popSafe()" will leak.
Note: ~Queue actually cleans up storage via manual call to destructors.
```
virtual ~Queue() {
while (!empty()) {
Entry* e = pop();
e->data().~T();
delete e;
}
delete tail;
}
```
2. std_shared_ptr<void>
peer.h:
```
std::unordered_map<std::string, std::shared_ptr<void>> data_;
```
Notice the "void". When that is hash table is destroyed, the shared_ptrs will not destroy objects.
putData does:
```
void
Handler::onConnection(const …
```

https://github.com/oktal/pistache/issues/399

---

include/pistache/async.h
include/pistache/client.h
include/pistache/optional.h
src/client/client.cc
src/common/net.cc
src/common/transport.cc

Remaining issues in test_memcheck
Follow up for: https://github.com/oktal/pistache/issues/399
No issues remaining in 'test_memcheck' after this. (note: hopefully test coverage is sufficient)
1. include/pistache/async.h
- Memory leak - data allocated in 'Core' was never freed.
2.include/pistache/client.h
- Leak of ' const struct sockaddr* addr' - if the leak is fixed then this becomes an 'invalid read'
- Solution - make a local storage in the class and copy data over.
3. include/pistache/optional.h
- Uninitialized data read - data() is uninitialized if nothing was constructed there - the condition was dangerous - copied logic from normal operator= in same class.
4. src/client/client.cc
- Fix continuation for item 2.
- Fix actual leak source -> getaddrinfo leaked the 'addrs' - that needs to …

Fix issues in test_memcheck

---

.travis.yml

Before this fix the coverage test was just passing in one of build jobs and there was unnecessary files inside tests/* and googletest-release-1.7.0/* folders. Supported compilers:
- clang-4.0 (error, maybe lcov version)
- clang-5.0 (error, maybe lcov version)
- clang-6.0 (error, maybe lcov version)
- g++-4.9 (done)
- g++-5 (done)
- g++-6 (done)
- g++-7 (done)
- g++-8 (error, maybe lcov version)

Fixing coverage support to compiler matrix and removed coverage of unnecessary files.

---

include/pistache/stream.h

Small fix to allow compilation with gcc's -Wcast-qual warning, and treating all warnings as errors.

Fixing case where const was cast away

---

.gitignore
include/pistache/http.h
src/client/client.cc
src/common/http.cc
tests/http_client_test.cc

When client requests
keep-alive: the answer from the server is keep-alive and the connection remains open
close: the answer from the server is close and connection is closed
ext: the answer from the server is ext and connection is closed (I don't really know what exactly should be the behaviour of the server when connection is like this; so this follows default: close connection).
When no Connection header is specified the server closed the connection by default.

Attempt to fix HTTP connection header handling.

---

include/pistache/http.h
src/common/http.cc

Hi,
on building Pistache I always get a -Wreorder warning in gcc. Here is a fix to get rid of it.

fix: -Wreorder warning on gcc

---

examples/http_server.cc
include/pistache/common.h
src/client/client.cc
tests/http_server_test.cc

In this PR I'm fixing memory defects in http server tests. At the current time we should explicitly set timeout to avoid memory defects on client. I will continue investigation of possible memory defects in client.

Fix memory defects in http server tests

---

src/client/client.cc

Fix memory leak in client: lambda holds shared_ptr and memory isn't freed (Connection)

Fix memory leak in client: lambda holds shared_ptr

---

include/pistache/router.h
src/server/router.cc

This improvement could simplify adding routes at runtime from a dynamically loaded module.
Instead of classifying routes by method by method through a conditional statement. This could simplify, just by creating a dictionary of routes and adding strongly typed method information to it.

Exposing Router::addRoute

---

src/client/client.cc
tests/payload_test.cc

In payload_test `client` and `resultsetMutex` should be in the same scope because `resultsetMutex` is captured by lambda that can be call during client desctruction.

Fixing error handling in client and payload test

---

include/pistache/client.h
include/pistache/os.h
src/client/client.cc
src/common/os.cc
src/common/reactor.cc
src/server/listener.cc

In this PR have made refactoring to improve API and code structure:
1) I've removed several magic numbers: `size` value that is passed to `epoll_create` is a hint and used for backward compatibility (see [here](http://man7.org/linux/man-pages/man2/epoll_create.2.html)).
2) I've changed `timeout` default value in `Epoll::poll` to wait infinity: this behavior is closer to how it's used in Pistache.
3) Pass `Const::MaxEvents` value to `maxevents` of `epoll_wait` function that is equal to `events` array size otherwise we should have additional check that the real size of array is greater or equal to `maxevents` (to prevent out of bound array access).
4) I've improved `Transport::onReady`, extract several methods because a lot of nested `if`'s look cumbersome + added assert's.

Refactoing in Client and Epoll

---

src/common/stream.cc

This patches the issue described in #298 (Segment fault in Pistache::DynamicStreamBuf::overflow).

Fixes Segment fault in Pistache::DynamicStreamBuf::overflow #298

---

src/common/stream.cc

ARM build was broken due to type mismatch in std::max (32 vs 64 bit long size).

Fix ARM build issue (type mismatch in std::max)

---

README.md
quickstart.html

Fixed stable PPA name. It was wrong in the README.md and on the website.

Kip debianization

---

tests/listener_test.cc

When compiling on Alpine linux which use the musl library, listener_test fails.
It expects to have "Address already in use" from perror but instead have
"Address in use".
This commit tests if either string is returned.

fix tests/listener_test for musl c library

---

include/pistache/http.h
include/pistache/router.h
src/server/router.cc
tests/rest_server_test.cc

If the REST router cannot find an exact match for the requested method
and resource, it will search for other methods that support the
resource. If another method supporting the resource is found, router
will send a HTTP 405 response to the client.
Also added a unit test to exercise REST server response code support.

Add support for HTTP 405 responses from the REST server

---

src/common/transport.cc

Related to recent unit test intermittent failures.
Handles a condition where the file descriptor for a connection is closed
before all processing is done, leading to an error. This is usually the
result of multiple exceptions being thrown by the HTTP parser without a
connection being set to `Keep-Alive`.
In the error case the HTTP parser code closes the file descriptor but there are multiple replies in flight internally. Previously when the `send()` call failed, Pistache would still try to modify the file descriptor which lead to an error from the `epoll` code. This change modifies the cleanup code when a bad file descriptor is detected during send to skip trying to modify the file descriptor.
Closes #501 (same error message) and makes the unit tests reliable again.

Add error handling in cases of writing to an invalid file descriptor

---

include/pistache/net.h
src/common/net.cc
tests/net_test.cc

Currently untested, but should work and be backwards compatible-ish.
* Unifies Ipv4 and Ipv6 classes into IP class
* Swaps out std::string host_ for the new IP class as the backing store for Address class

Some clean-up of the net primitives

---

examples/CMakeLists.txt
examples/hello_server.cc
examples/http_server.cc
examples/http_server_shutdown.cc
examples/rest_description.cc
examples/rest_server.cc
include/pistache/tcp.h
src/common/os.cc
src/server/listener.cc
tests/cookie_test_3.cc
tests/http_client_test.cc
tests/http_server_test.cc
tests/https_server_test.cc
tests/rest_server_test.cc

(see discussion in #221)
Also remove unreachable shutdown() from examples and add
http_server_shutdown example with signal handling (thanks to 1Hyena).

remove broken Tcp::Options::InstallSignalHandler

---

include/pistache/http.h

Found this when I was hunting for something else. Adding a destructor with disarm() to Timeout class to avoid a use-after-free error. To replicate error, run run_http_server example, curl to localhost:9080/timeout, and ctrl-c immediately.

Timeout use-after-free error

---

src/common/http_header.cc

Changing incorrect conversion stoi to stoull. this was causing issue when Content-Length was larger than 2GB (continuation of maxRequestSize pull)

Content-Length parsing used incorrect conversion function

---

include/pistache/async.h
tests/async_test.cc

This is trying to solve the same problem as #337 
- Added the test from that issue
- Changed the chain handling behaviour to immediately increment the reject counter, and to just return if an attempt is made to reject the promise already (as it's already been rejected).
I'm not 100% sure that this is the right approach, but it works for my workload (hundreds of short and very long (>4 minute) requests, with clients disconnecting mid-request. It also passes all the unit tests.
I just think this needs a code review from someone who understands the promise system more deeply than I do.

Recursive rejects

---

CMakeLists.txt

I'm using pistache as a git submodule, and using it from my CMakeLists.txt with
`add_subdirectory(external/pistache)`
As a result of this I'm getting a lot of targets, which look uncessary from my POV.
Targets exported by pistache/CMakeLists.txt
```
Continuous
ContinuousBuild
ContinuousConfigure
ContinuousCoverage
ContinuousMemCheck
ContinuousStart
ContinuousSubmit
ContinuousTest
ContinuousUpdate
Experimental
ExperimentalBuild
ExperimentalConfigure
ExperimentalCoverage
ExperimentalMemCheck
ExperimentalStart
ExperimentalSubmit
ExperimentalTest
ExperimentalUpdate
Nightly
NightlyBuild
NightlyConfigure
NightlyCoverage
NightlyMemCheck
NightlyMemoryCheck
NightlyStart
NightlySubmit
NightlyTest
NightlyUpdate
coverage
dist
test_memcheck
pistache
pistache_shared
pistache_static
```
Another issue …

CMake: disable test targets when not testing

---

src/common/net.cc

There's no guarantee that `host_` is long enough for the `INET_ADDRSTRLEN` (or `INET6_ADDRSTRLEN`, respectively) memcpy to be valid, and in any event there doesn't seem to be a reason to copy it in the first place.

Remove broken memcpy in Address::init

---

include/pistache/peer.h
src/common/peer.cc
tests/rest_server_test.cc

Adds automatic peer hostname resolution, as `Peer::hostname_` is not currently populated by any means.
This removes the const-ness of ::hostname() and the ostream printer. I thought about adding a '::resolveHostname()' method, but if someone asks for the hostname, resolution will need to happen regardless.
Added a unit test, but it may fail as it assumes that the resolution sequence ("localhost" -> ip -> hostname), hostname = "localhost".

Adding hostname resolution to peer

---

src/common/http.cc

Having Http close the fd on the peer without cleaning up Transport::peers means the following:
- First client connects, and gets fd X.
- Peer information is generated from this connection, and is inserted into Transport::peers<fd, Peer>
- Client request is served, and Http calls close on fd X, but doesn't clean up Transport::peers
- Second client connects, and fd X is reused.
- Transport::peers isn't updated, as it already exists.
- Now the peer associated with client 2 wrongly contains the info from client 1.
I opted to remove Http's closing of the fd, since it shouldn't be releasing resources that it doesn't own. FD closing and peers cleanup is handled by Transport::handlePeerDisconnection().
If there are clients out there that rely on the server disconnecting the TCP session after the …

Removing Http's close of open fd

---

include/pistache/endpoint.h
include/pistache/listener.h
include/pistache/reactor.h
src/common/reactor.cc
src/server/endpoint.cc
src/server/listener.cc
tests/CMakeLists.txt
tests/threadname_test.cc

Setting the thread name on the server mode, it can be used to set a unique name for a thread, which can be useful for debugging  multi-threaded applications, if you are starting more than one server on different ports (the threads on each port cab be set by one name) .
**.threadsName("MyHTTPServer")**
Usage : 
```
std::shared_ptr<Http::Endpoint> mHttpEndpoint_;
auto opts = Http::Endpoint::options()
.threads(3)
.threadsName("MyHTTPServer")
mHttpEndpoint_->init(opts);
```

Set Thread name for running HTTP server threads

---

CMakeModules/FindRapidJSON.cmake

`find_package_handle_standard_args()` could not be used without include of `FindPackageHandleStandardArgs`. See #597

CMake: fix RapidJSON package search. Fixes #597

---

tests/optional_test.cc

Adds `Pistache::Optional` integer test cases for issue https://github.com/oktal/pistache/issues/505.

Add test cases for Pistache::Optional integer

---

src/common/stream.cc
tests/stream_test.cc

e.g. DynamicStreamBuf passes pointer to internal vector, but RawBuffer
treats it as a null-terminated string, trying to read one char beyond.
Running provided unit-test under valgrind produced
> [ RUN      ] stream.test_dyn_buffer
> ==4206== Invalid read of size 1
> ==4206==    at 0x4C2EA70: memcpy@@GLIBC_2.14 (vg_replace_strmem.c:1035)
> ==4206==    by 0x442B1B: std::string::assign(char const*, unsigned long) (in /home/vbespalov/source/utils/pistache/build/tests/run_stream_test)
> ==4206==    by 0x4428DC: Pistache::RawBuffer::RawBuffer(char const*, unsigned long, bool) (in /home/vbespalov/source/utils/pistache/build/tests/run_stream_test)
> ==4206==    by 0x41ED7C: stream_test_dyn_buffer_Test::TestBody() (in /home/vbespalov/source/utils/pistache/build/tests/run_stream_test)
> ==4206== …

Fix access beyond passed buffer when constructing RawBuffer

---

include/pistache/utils.h
src/common/transport.cc
src/common/utils.cc

This patch fixes the behavior of serveFile with SSL enabled servers.
Before, the sendfile(2) syscall was used, but cannot work if our current
version of OpenSSL, because the transfer happens kernel-side, and the
SSL encryption does not. So I've implemented a _very_ basic sendfile
utility for SSL connections, which only stream 4096 bytes of the file
per call, in order not to block the whole pipeline.
It's worth noting that this patch will be useless when the upstream
moves to OpenSSL 3.0, which uses Kernel TLS, and implement a zero-copy
version of SSL_sendfile, which is far more superior than the one
implemented in this patch.
I've tested the basic use cases with this patch, whis is file
downloading. I've used small and big (45G) files, and it appears to be
working.
I've launched kip's …

Transport: Fix static file serving from SSL connections

---

src/common/utils.cc

Due to a brain-lag on my end, I've introduced a regression in commit
44e40478d604746963b898efd463a541ebbea824, because a SSL utility function
was compiling whether or not the SSL was enabled. It is now fixed,
apologies.
Pull Request: https://github.com/oktal/pistache/pull/623
Fixes: https://github.com/oktal/pistache/issues/621
Fixes: https://github.com/oktal/pistache/issues/622
Fork: Fork: https://git.mobley.ne02ptzero.me/~louis/pistache
Signed-off-by: Louis Solofrizzo <lsolofrizzo@online.net>

Common: Fix broken compilation for trees without the PISTACHE_USE_SSL option

---

include/pistache/http_headers.h
src/common/http.cc
src/common/http_headers.cc
tests/headers_test.cc

fixes #604
I'm using pistache with nginx, with HTTP2 -> nginx proxy -> Pistache. As HTTP2 lowercases all headers, Cookie and other raw headers weren't working.
This PR:
* Adds case-insensitive matching for the Cookie and Set-Cookie header
* Adds case-insensitive lookups/hashing for rawHeaders
* Refactors the case-insensitive comparing to use less memory (_how is this actually not in c++ officially, omg_)
* Adds tests for raw headers and cookies

Raw and Cookie header case-insensitive

---

src/common/net.cc
tests/net_test.cc

As discussed in https://github.com/oktal/pistache/issues/625

Allow IPv6 addresses without port number. Fixes oktal/pistache#625

---

include/pistache/async.h
src/common/transport.cc

I am experiencing an issue with a single worker thread pistache server, debug build. I am serving a simple web page. I connect to the web page and repeatedly press refresh (F5) on my browser (Firefox). After a couple of resets I get a segfault.
Looking through the call stack and after some analysis, it seems that there is a promise created that captures its local scope. In edge cases, the promise would resolve after the object was deleted. The internal "Core" shared pointer would be cleared and this would lead to the segmentation fault.
The trigger for this case is getting an EPIPE or ECONNRESET, which should probably not be issuing a response anyhow since the fd is broken.
I can see that lambdas capturing the entire local scope is common in the code base. I would suggest that you avoid …

Fix for segmentation fault caused by incorrect lambda capture in promise

---

include/pistache/mime.h

https://json-schema.org/latest/json-schema-core.html#rfc.section.13
(more precisely, draft-handrews-json-schema-02 of that document)
defines two new MIME subtypes that descibe JSON schema documents and
instances of JSON schema documents.
This patch adds them to mime.h.

add JSON schema MIME types

---

include/pistache/optional.h
tests/optional_test.cc

1st commit : I don't think we need the extra type U which is only provided to has_equalto_operator<U> metafunction.
2nd commit : when a user provides a non-comparable type, then we state what they've done wrong instead of letting a compiler complain about the lack of operator== in optional<T>.
3rd commit : previous didn't test optional
However, now has_equalto_operator<Optional<not_comparable>>::value will return a different value (but it's still technically correct) :D @muttleyxd what do you think?

optional::operator== improvements

---

include/pistache/os.h
src/common/os.cc
src/server/listener.cc

This PR introduces changes which resolve these issues (#38, #43, #150, #164, #221).
the file descriptor will stay open at the end of the Listener and Epoll life-time, there for the shutdown will not work properly, and may get the Bad file descriptor in multi threading and also Too many open files. 
it just close the listener port and FD and close FD in epoll deconstructor.

close non-closed file descriptor will resolve : #38, #43, #150, #164, #221 - shutdown will work properly 

---

examples/custom_header.cc

Alpine defines macros 'major' & 'minor', so the functions modified are
parsed as macro invocations. The rename avoids this collision.

Avoid macro invocation in examples

---

include/pistache/stream.h
src/client/client.cc
src/common/http_header.cc

This change makes it simpler to deduce string length when it's possible and void a macro.

added an overlaod for match_string

---

include/pistache/http_defs.h
include/pistache/http_header.h
tests/headers_test.cc

The rest is fallout / fix ups due to that.

Declared CacheDirective single-argument constructor as 'explicit'.

---

CMakeLists.txt
include/pistache/net.h
src/CMakeLists.txt

I haven't tested the built library in practice yet, but at least it compiles on Android now.
* Clang workaround to disable C++17 (and compile with C++14 instead) broke the build due to conflicts in pistache's `string_view` implementation. Luckily the WA is not necessary with Clang 8 anymore and hence is enabled for old compiler versions only now. (Clang 7 has not been tested but is assumed to be fine).
* net.h was missing an include for `struct sockaddr_in`
* `pthreads` dependency is now discovered using CMake's FindThreads module (required on Android since pthreads is built into the core NDK and hence requires no explicit link flags)

Fix Android build

---

src/common/reactor.cc

I am using Pistache with [ROS](https://www.ros.org/), in [ubuntu xenial](http://br.releases.ubuntu.com/16.04/), so I need C++14, I want to use the GCC version distributed for my current system. When I started, I searched for other libraries to do the same, but Pistache was the best, considering simplicity, compatibility and features, so nice work to you all!
This is just a patch to allow the Pistache library to still be compiled with c++14. In my opinion, even thought we are in 2020, as this is an API, a higher compatibility should be aimed.
Hoping that you accept my PR,
closes #666 @dennisjenkins75 @kiplingw

Modify reactor.cc to c++14

---

include/pistache/stream.h
include/pistache/view.h
src/client/client.cc
src/common/stream.cc

When used like &vec[0], there would be an assert in gnu std lib:
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type)
[with _Tp = char; _Alloc = std::allocator<char>; std::vector<_Tp, _Alloc>::reference = char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]:
Assertion '__builtin_expect(__n < this->size(), true)' failed.
on the other hand, using .data() is allowed even on empty uninited vectors
array<> access is modified for consistency.

Address array and vector storage through .data()

---

include/pistache/client.h
src/client/client.cc

Hello,
In my opinion the following relationship between classes can be removed:
```
friend class ConnectionPool;
```
Instead it, I'm proposing to use corresponding methods. If I'm not mistaken it would be better to hide the internal states of objects.

Remove friend relationship in Connection class

---

include/pistache/client.h
src/client/client.cc

Hello,
From my point of view, `Transport` class can be considered as an implementation detail and shouldn't be exposed in `client.h` header. I don't consider it as a part of public API. What do you think about it?

Move client Transport to client.cpp file

---

src/client/client.cc

It's possible that `parse()` method can throw an exception. In the current client implementation uncaught exception can happen.

Handle exceptions on responce parse in client

---

include/pistache/http.h
src/common/http.cc

1) Replaced inheritance to compisition in `ResponseStream` and `ResponseWriter`;
2) Fixed `/* @Refactor: code duplication */` comment: extracted `sendImpl` method in `ResponseWriter` class;
3) Move method definitions for `ResponseStream` and `ResponseWriter` to `http.cc`.

Refactoring in http.h and http.cc

---

include/pistache/async.h
include/pistache/router.h

Previosuly, I held off on "async.h", because formatting async.h caused cppcheck-1.88 to segfault.  I've updated my cppcheck.  This PR is partially to test which cppcheck is used by travis.  If it does not crash the CI, then I might merge this PR.

Ran clang-format on all headers (except date.h, since its not ours).

---

include/pistache/net.h
include/pistache/peer.h
src/common/net.cc
src/common/peer.cc
src/server/listener.cc

1) Code simplification in `Listener` and `Peer`: in my opiniton it would be better create `Peer` only using factory method and not allow user to associate some date (for instance, `fd`) later;
2) Add `fromUnix` overloading to `Address` to improve code in `Listener`;
3) Add `client_fd`socket  closing in the case when memory for SSL cannot be allocated.

Code simplification in Peer class and small fix in Listener

---

include/pistache/peer.h
src/common/peer.cc
src/common/transport.cc
src/server/listener.cc

Hello,
I this pull request I'm doing two things:
1) Improved `Peer` API in case of SSL;
2) Delete `associateSSL` call because I consider it useless, `SSL_free` will be called in `Peer` destructor.
What do you think about these changes?

Improve Peer SSL API and remove unnecessary code

---

.travis.yml

Currently Travis CI is only building on amd64. This adds [support](https://docs.travis-ci.com/user/multi-cpu-architectures/) for IBM Z series (`s390x`), IBM POWER 8 / 9 (`ppc64el`, aka ppc64el in Travis' nomenclature), and ARMv8 (`arm64`). This is necessary in order to more reliably screen for portability issues.

Tell Travis to build on all of its supported CPU architectures.

---

include/pistache/router.h

Current `clone` method implementation in `RouterHandler` class does not clone base part of `RouterHandler`, default `Http::Handler` constructor is called.

Fix clone method in RounterHandler

---

include/pistache/http.h
src/common/http.cc

1) Deleted `associatePeer` method in `Timeout` and assign peer in `Timeout` contructor;
2) Added using `default`for contructors in the places where it's possible;
3) Added `transport` pointer check to `disarm' method.

Code simplification + add pointer check

---

include/pistache/route_bind.h
include/pistache/router.h
tests/router_test.cc

`std::bind()` can handle `std::shared_ptr`s just fine, so at first I expected `Routes::bind()` to handle them as well. However, it does not, since it simply doesn't actually use `std::bind()`.

Add version of bind() that can bind to shared_ptrs

---

.travis.yml
include/pistache/http.h
src/common/http.cc
tests/http_server_test.cc

1. Add method ResponseWriter::getResponseSize() (returns size_t)
1. Add method ResponseWriter::getResponseCode() (returns Http::Code)
1. Added unit test of the same.
1. Formatted the 3 modified files w/ clang-format
This addresses an issue raised in https://github.com/oktal/pistache/pull/695

ResponseWriter caputres response size (bytes) for use after send().

---

tests/http_server_test.cc

Fix the following warnings:
```
/home/travis/build/oktal/pistache/tests/http_server_test.cc:407:3:   required from here
/home/travis/build/oktal/pistache/third-party/googletest/include/gtest/gtest.h:1585:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```
and
```
/home/travis/build/oktal/pistache/tests/http_server_test.cc:408:3:   required from here
/home/travis/build/oktal/pistache/third-party/googletest/include/gtest/gtest.h:1581:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

Fix comparison between signed and unsigned integer expressions warnings

---

src/server/listener.cc
tests/http_server_test.cc
tests/https_server_test.cc

1) Added additional check to `Listener::bind` to handle the case when socket creation is failed
2) Added more logs to debug flaky `http_server_test.multiple_client_with_requests_to_multithreaded_server` test
3) Improved https test and fixed warning

Exploring flaky tests: more logs and several improvements

---

include/pistache/client.h
include/pistache/http.h
include/pistache/peer.h
src/common/http.cc
src/common/peer.cc
tests/http_parsing_test.cc
tests/rest_server_test.cc

I'm proposing the following code improvements:
1) Introduced in `Http` namespace correspondent parser classes `Parser`, `RequestParser`, `ResponseParser` instead of using entities from `Private` namespace in different parts of code;
2) Removed several `friend` relationships between classes;
3) Added a unit test for checking parser reset.
It looks that code compatibitily shouldn't be broken after these changes, but it would be better to double check it.

Code improvements in HTTP Parsers

---

CMakeLists.txt
include/pistache/optional.h
tests/optional_test.cc

Related to #658 
I know cppcheck is a nice tool, but it's wrong in this specific case - not all constructors should be explicit.
`Pistache::Some` and `Pistache::None` are helper functions which allow to create an optional value.
But if our constructors have to be always explicit then what's the need for these functions?
We could just create a marker like `Pistache::Nullopt` and get rid of these two, if we want to have everything explicit (which doesn't really make sense, since you should be able to do an assigment).
#658 has blocked following syntax
```
Pistache::Optional<int> value = Pistache::Some(10);
```
now we need to do
```
Pistache::Optional<int> value = Pistache::Optional<int>(Pistache::Some(10));
```
which is inefficient, of course we could shorten it by using `auto`
```
auto …
```

optional: make Some and None constructors implicit

---

src/common/net.cc
src/server/listener.cc

1) Set `struct addrinfo` to zero, as required in [man](http://man7.org/linux/man-pages/man3/getaddrinfo.3.html);
2) Apply clang-format to `net.cc` (I forgot to do it in the previous PR).

Set addrinfo to zero and clang format for net.cc

---

include/pistache/http.h

I my opinion, `onInput` method must be `private` in Http `Handler`.
For instance, now, it's possible for Pistache user to override this method:
```
class CustomHandler : public Http::Handler {
public:
HTTP_PROTOTYPE(CustomHandler)
...
void onInput(const char *buffer, size_t len,
const std::shared_ptr<Tcp::Peer> &peer) override;
...
```
and as a result everything will be broken. `onInput` method is part of implementation and shouldn't be exposed for user.

Make onInput private in Http handler

---

include/pistache/http.h
include/pistache/net.h

Hello,
I have read [Http Handler](http://pistache.io/guide/#http-handler) part of Pistache user guide and understood that `onConnection` and `onDisconnection` methods are not part of public API. `onConnection` method is part of implementation:
```
void Handler::onConnection(const std::shared_ptr<Tcp::Peer> &peer) {
peer->putData(ParserData, std::make_shared<RequestParser>(maxRequestSize_));
}
```
That's why they must be `private` and client shouldn't have permissions to use them. Moreover, there are plenty of internal details that can be access by client in Peer object.
Also I'm proposing to move `httpAddr` to `net.h`. I think it's better place for this code.

Changes in Http: make onConnection and onDisconnection methods private

---

src/common/net.cc

Based on [this](https://en.cppreference.com/w/cpp/language/static_assert) documentation the following `static_assert` implementation:
```
static_assert ( bool_constexpr , message ) 		(since C++11)
```
should be used in Pistache to be compatible with C++11/14.

Fix static_assert (C++17 -> C++11) in net.cc

---

CMakeLists.txt
include/pistache/base64.h

Hi guys,
This PR is somehow a following from this [one](https://github.com/oktal/pistache/pull/725), bringing the code back to cxx14.
So here is my proposal to bring the code to cxx14: 
- Extend std with byte, avoiding large changes on modification proposed by @kiplingw  [here](https://github.com/oktal/pistache/pull/725)
- Force CMakeLists.txt to compile CXX14 (When you decide to move to CXX17 chage it), I did this so we guarantee that the only compilable version will be on CXX14 and will be "clear" to the developers the current CXX version. Also it will be easier to see on PR's)
What you think @kiplingw and @dennisjenkins75?
Thanks

Bring the modifications to cxx14

---

CMakeLists.txt
examples/http_server.cc
examples/rest_description.cc
examples/rest_server.cc
include/pistache/common.h
include/pistache/date.h
include/pistache/string_view.h
src/client/client.cc
src/common/base64.cc
src/common/http_header.cc
src/common/net.cc
src/common/os.cc
src/common/reactor.cc
src/common/stream.cc
src/common/transport.cc
src/common/utils.cc
src/server/listener.cc
tests/async_test.cc
tests/httplib.h
tests/rest_server_test.cc
tests/streaming_test.cc

Add `-Wconversion` compilation flag and fix related warnings, mainly by adding `static_cast` in problematic locations.
After this PR, there are still quite a few type conversion warnings remain:
1. `async.h:465` - deep template parameters usage, I could not find a good cast
2. `date.h:1641`, `:1642` - I could not find a good way to cast to a bit field
3. A lot of `-Wconversion` warnings appear when compiling RapidJson library. Not fixed in this PR

Add -Wconversion compilation flag and fix related warnings (originated by #733)

---

include/pistache/endpoint.h
include/pistache/listener.h
include/pistache/ssl_wrappers.h
src/server/endpoint.cc
src/server/listener.cc

1) Added using RAII for working with `SSL_CTX` and cleaning resources automatically.
2) Minor code improvements.
3) It's a good time to think about using `EVP_cleanup();`. Is it required? (see my comment with https://www.openssl.org/news/changelog.txt link)

SSL usage improvements: using RAII for ssl context resource

---

src/server/listener.cc

A race exists between the runThreaded and shutdown/dtor as follows:
runThreaded - called
shutdown - called
shutdown - check for shutdownFd.isBound returns false (so no notify)
runThreaded - thread executing 'run' starts
runThreaded - thread calls shutdownFd.bind
shutdown - blocks waiting for run thread
runThreaded - continues to run as no notification received
This deadlock avoided by ensuring the shutdownFd.bind is called before
the thread is created rather than doing it at the start of the thread's
execution.

Fix shutdown data race in listner.cc

---

src/common/http.cc
src/common/http_defs.cc

Fix warnings occurring in gcc, described in #748

Fix -wConversion warnings #748

---

.travis.yml

I saw your comment on #762 regarding failing Travis builds and I tried to solve it.
Seems like the issue is that you were loading a `trusty` clang pipeline, which is for Ubuntu 14.04 LTS but at the top of the travis.yml you specify `bionic` which is Ubuntu 18.04 LTS, so I fixed the clang pipeline to use `bionic` too.
This issue seems the same that a guy was reporting here: https://travis-ci.community/t/cannot-apt-get-install-clang-5-0/3250/3
That time (1 year ago) the suggestion was to switch from `trusty` to `xenial` (Ubuntu 16.04 LTS) or, in alternative, to add `dist: trusty` at the top of the file to keep using `trusty` but, since you are already using `bionic`, this suggest didn't seem to fit in your build system.

Fixing broken TravisCI builds for the clang toolchain

---

CMakeLists.txt

Hi,
Here is the patch for RaspberryPi 4 discussed in #762.
Below I'm attaching a build log. I ran the tests too, everything seems alright but I couldn't get memory check to work property using valgrind. It was taking so long with the first test that I just aborted it after 20 minutes :) I think the raspberrypi is too small to run such kind of tests.
[build.log](https://github.com/oktal/pistache/files/4617836/build.log)
Also, I had a look at adding a TravisCI profile to build raspberrypi-compatible binaries but it's non trivial unfortunately because RaspberryPi runs on ARM architecture. One way is to emulate ARM using QEMU on a x86 processor, this will make the build reaaaally slow though (https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html).
Then I found out that TravisCI …

RaspberryPi4 Mobel B linker fix #762

---

include/pistache/endpoint.h
include/pistache/listener.h
include/pistache/log.h
include/pistache/ssl_wrappers.h
src/common/log.cc
src/server/endpoint.cc
src/server/listener.cc
tests/CMakeLists.txt
tests/logger_test.cc

Implement a logging API using a collection of PISTACHE_LOG* macros to be used internally.
Users of pre-compiled Pistache can provide an alternative implementation of a LogHandler to direct log messages as required. Users compiling Pistache can include patches to modify the PISTACHE_LOG* macros to use an alternative logging engine if required.
This PR also includes additions to the ssl wrappers to handle OpenSSL BIO objects and some other SSL helpers.

Logging api - addresses issue #771

---

.travis.yml

Previously, Travis would only attempt to collect coredumps from the last
directory the build script was in, or the home directory. This meant
that most coredumps were missed, and debug information was lost.

Travis fix to collect coredumps from build configuration subdirs - #720

---

include/pistache/reactor.h
src/common/reactor.cc
src/common/transport.cc
src/server/listener.cc

An error existed in transport.cc where it incorrectly assumed that
it would not receive epoll events relating to a closed peer
connection. This is not the case because file descriptors can be
shared between processes e.g. on exec. When they are, events could
still be generated. The solution is to explicitly de-register our
interest in the file descriptor before we close it using
epoll_ctl(EPOLL_CTL_DEL). In addition the call to accept in
listener.cc has been updated to set CLOEXEC on the peer file
descriptors as these should not be shared with other processes
anyway.

Ensure no epoll events are processed for closed peer files

---

include/pistache/string_view.h
include/pistache/transport.h
src/client/client.cc
src/common/http.cc
src/common/transport.cc
tests/streaming_test.cc

Very wonky attempt at fixing #786.
`transport_->asyncWrite()` seems to put current buffer to write queue instead of dumping it straight into socket. This isn't a good fix, since we won't dump queued items. @dennisjenkins75 I think you may have a better insight, how it should be done, but `Tcp::Transport` is magic to me at the moment.
However it works fine with following example.
```cpp
#include <chrono>
#include <thread>
#include "pistache/endpoint.h"
using namespace Pistache;
class HelloHandler : public Http::Handler {
public:
HTTP_PROTOTYPE(HelloHandler)
void onRequest(const Http::Request& request, Http::ResponseWriter response) override
{
UNUSED(request);
auto stream = response.stream(Http::Code::Ok);
stream << "Hello ";
stream.flush(); …
```

Fix ResponseStream flush

---

include/pistache/transport.h
src/common/transport.cc

In this PR I'm proposing refactoring in `asyncWriteImpl` method: extracting two methods `sendRawBuffer` and `sendFile` to improve code readability.

Small refactoring in asyncWriteImpl

---

include/pistache/stream.h
include/pistache/transport.h
src/common/stream.cc
tests/stream_test.cc

Hello,
In the is Pull request I'm proposing refactoring in `RawBuffer`.
1) I found `isDetached` method as useless and decided to remove it: what's the reason of using it?
2) Removed redundant `BufferHolder` copy in `Async::Promise<ssize_t>`: `buffer` is already a _copy_ bacause captured by value (`[=]`);
3) Renamed `detach` to `copy` - from my point of view `copy` is more intuative;
4) Removed obsolete tests and added new ones.

Raw buffer refactoring

---

.travis.yml

LLVM style is set explicitly as I found out that clang-format default style on my Debian is Google style (idk why, can't find any config for this behavior). And LLVM style is used already in Pistache that's why it's set explicitly.
Comparison is performed based on diff, so only modified lines are checked, not the whole file. Once everything is formatted properly, full check is useless, hence next PR should clang-format all the header and source code files.
Check is performed on pull requests only.
Failure example:

Check pull requests source code formatting

---

CMakeLists.txt

This will fix the detection of atomic:
```
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Failed
-- Looking for __atomic_load_8 in atomic
-- Looking for __atomic_load_8 in atomic - not found
CMake Error at CMakeModules/CheckAtomic.cmake:76 (message):
Host compiler appears to require libatomic for 64-bit operations, but
cannot find it.
Call Stack (most recent call first):
CMakeLists.txt:19 (include)
```
Indeed if C language is not enabled, the test will be run with the C++ compiler resulting in the following error:
```
Building CXX object CMakeFiles/cmTC_fad22.dir/CheckFunctionExists.cxx.o
/tmp/instance-0/output-1/host/bin/mipsel-linux-g++ --sysroot=/tmp/instance-0/output-1/host/mipsel-buildroot-linux-gnu/sysroot    -D_LARGEFILE_SOURCE …
```

CMakeLists.txt: add C language to project statement

---

include/pistache/http.h
src/client/client.cc
src/common/http.cc

Use a std::shared_ptr<std::string> instead of std::string for the body_ member variable in Pistache::Http::Message
As a Pistache::Http::Message object is copied several times during the handling of a request this leads to a significant reduction in memory usage when uploading files through a http post.

Use a std::shared_ptr<std::string> for the body_ member variable in Pistache::Http::Message

---

include/pistache/http.h
src/client/client.cc
src/common/http.cc

Reverts oktal/pistache#814
Causes breakage for two users of pistache.

Revert "Use a std::shared_ptr<std::string> for the body_ member variable in Pistache::Http::Message"

---

include/pistache/client.h
src/client/client.cc

The client implementation isn't compliant with HTTP 1.1 standard, to be
specific, it doesn't honor the "Connection: close" response header. As a
result, whenever a new request is sent, a new tcp connection is opened
to the server and is never closed (unless the server close it).
The best place to close the connection is in Connection::OnDone() method,
however, that method is provided too early, in the Connection::asyncPerform()
method, where the Http::Response object is not yet available. It's also
incorrect to blindly close the connection in OnDone() method, as there might
be more data from server.
This commit explicitly closes all opened connections on Client::shutdown(),
to guarantee all network resources are recycled on that call.
It's impossible to write any unit test case verify it, …

fix issue-193

---

CMakeLists.txt
src/CMakeLists.txt

Don't build and install pistache_shared if the standard cmake
BUILD_SHARED_LIBS is set to OFF
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

CMakeLists.txt: respect BUILD_SHARED_LIBS

---

include/pistache/http.h
src/common/http.cc

The handling of chunked transfer-encoding is broken. 
The usage of complete body_.size() seems to be always wrong. I don't know why this has worked in the first place, maybe only if there is one chunk?
I introduced a separate variable to count the already received bytes of the chunk.
A second bug was at the condition to check, whether the chunk could be completely appended, since the chunk size exclude the trailing /r/n, but we need to have that /r/n, otherwise it is detected as the next start of a chunk (with a missing number of bytes, but this is interpreted as 0). Therefore, we need to check against (size +2).
The second bug is only triggered in very special situations, e.g. a very slow connection, or if the chunk size is bigger or the same as the proccesing buffer size (mhh thats not …

fix chunked transfer decoding

---

include/pistache/http.h
include/pistache/peer.h
src/common/http.cc
src/common/peer.cc
tests/http_server_test.cc

Building on PR #834 , this PR adds a per-connection identifier that makes it easier to keep track of which client is connecting, and reference their request.
Use case: Long-running queries can be assigned an ID, rather than using the peer FD (reused), which helps with debugging and provides an easier accounting method when cleaning up a long-running query's client disconnect before a full response has been generated.

Adding a Peer ID to identify connections

---

include/pistache/http.h
include/pistache/peer.h
src/common/http.cc
src/common/peer.cc

I have found that `Peer::getData`, `Peer::tryGetData` and `putData` are used only in one scenario (`Handler::onInput`) and decided that it's not needed to keep one key `__Parser` with `Http::Parser>` in std::unordered_map. Based on `Peer::putData` method logic only one parser can be inserted. Am I right?

Code simplification in RequestParser usage

---

tests/http_server_test.cc

In this PR I'm fixing #842 
1) Move server shutdown after delay to fix test;
2) Reading `handler->activeConnections.size()` and comparing with `0UL` is wrong is the test because changes for `activeConnections` happen in the **copy** of handler object (`ClientCountingHandler`).

Fix issue #842

---

include/pistache/peer.h

Now, I am thinking how to fix #798 issue and found that from client side `RequestParser` can be accessed, like:
```
void handleReady(const Rest::Request&, Http::ResponseWriter response)
{
cout << "Ready" << endl;
auto peer = response.peer();
if (peer)
{
auto parser = peer->getParser();
...
}
response.send(Http::Code::Ok); //, "1");
}
```
From my point of view it's bad, clients shouldn't have an access to internal details of handling http request.
I'm not sure that I'm proposing the best solution for this problem, but I think it's better than the current situation.

Forbid access to request parser object for clients

---

include/pistache/os.h
include/pistache/reactor.h
src/common/os.cc

The field `Fd fd;` of `Event` class is not used in code. The `fd` value is obtained from `tag` field.

Delete unused code and clang-format

---

include/pistache/http.h
include/pistache/peer.h
src/common/http.cc
src/common/peer.cc

In this PR I'm trying to get rid of unnessessary `Request` object copying to `ResponseWriter` and `Timeout` objects.
In my test cases (upload 4 different files with 5Mb):
before:
```
==39205== HEAP SUMMARY:
==39205==     in use at exit: 10,600 bytes in 75 blocks
==39205==   total heap usage: 10,538 allocs, 10,463 frees, 167,452,849 bytes allocated
```
after my changes:
```
==41875== HEAP SUMMARY:
==41875==     in use at exit: 10,600 bytes in 75 blocks
==41875==   total heap usage: 10,412 allocs, 10,337 frees, 127,442,493 bytes allocated
```

Fix issue #798 - Part 1: partially decrease allocated memory during file upload

---

include/pistache/http.h
src/common/http.cc

I think it would better to add getting request body by const reference.
In my test cases (upload 4 different files with 5Mb):
before:
```
==41875== HEAP SUMMARY:
==41875==     in use at exit: 10,600 bytes in 75 blocks
==41875==   total heap usage: 10,412 allocs, 10,337 frees, 127,442,493 bytes allocated
```
after my changes:
```
==50087== HEAP SUMMARY:
==50087==     in use at exit: 10,600 bytes in 75 blocks
==50087==   total heap usage: 10,410 allocs, 10,335 frees, 107,442,525 bytes allocated
```

Fix issue #798 - Part 2: Add getting request body by const reference

---

include/pistache/router.h
src/server/router.cc
tests/router_test.cc

- This exposes a mechanism for Rest::Router users to add handlers on client disconnection.
- Builds on prior work to expose `onDisconnection()` on `Http::Handler` (Rest::Router handler is in a Private namespace and isn't easily inheritable).
- Added unit test (the WaitHelper code is pretty cool, thanks @hyperxor )

Rest::Router add client disconnect handlers

---

CMakeLists.txt
debian/changelog

WIth this I'm trying to fix some of the issues pointed out in #827.
Changes:
Use `add_compile_options()` instead of modifying `CMAKE_CXX_FLAGS`.
Use `-Og` instead of `-O0` (from [gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html):
_"[-Og] is a better choice than -O0 for producing debuggable code because
some compiler passes that collect debug information are disabled at -O0"_)
Fix LTO check (previously it would fail because it checked only `CMAKE_CXX_FLAGS`. This didn't work when properly enabling LTO through `CMAKE_INTERPROCEDURAL_OPTIMIZATION`).
I'm not sure if I modified it correctly since I don't really understand
what that check is trying to do in the first place.
Check for Clang or GCC when applying compiler specific flags. …

Modernize CMakeLists.txt

---

CMakeLists.txt
src/CMakeLists.txt

For static library propose, fPIC is not mandatory, however, the current behavior is forcing it.
This PR brings fPIC as optional, but keeps it activated by default.

Make fPIC optional

---

include/pistache/tcp.h
src/server/listener.cc
tests/listener_test.cc

This solves following situation:
- we have a server using a Pistache, using port 9080
- one of endpoints uses fork() or some similar stuff to create a child process which runs in background (and can outlive its parent)
- endpoint gets called, child process is created
- server gets killed
- child lives on, blocking port 9080
- server cannot be restarted, because port 9080 is in use
example:
```
#include <cstdlib>
#include "pistache/endpoint.h"
using namespace Pistache;
class HelloHandler : public Http::Handler {
public:
HTTP_PROTOTYPE(HelloHandler)
void onRequest(const Http::Request&, Http::ResponseWriter response) override
{
std::system("sleep 1000 <&- &"); // fork magic - fire and forget style
response.send(Http::Code::Ok, "success");
}
};
int main()
{
Pistache::Address …
```

listener: add CloseOnExec option

---

.github/workflows/pistache.io.yaml
pistache.io/docs/headers.md
pistache.io/docusaurus.config.js
pistache.io/static/CNAME

This PR should fix the GitHub Action (installing yarn via npm and fixing the directory that the action would push to the `gh-pages` branch), as well as one dead link pointing to a nonexistent blog section and a note about `std::string_view` that really shouldn't be published with the documentation.
I tested everything on a clone of the repo, and everything seems to work ([pistache.pappacoda.it](https://pistache.pappacoda.it) is on and fine)

Fix #863 issues

---

.github/workflows/pistache.io.yaml

The workflow was triggered every time someone would make a PR, resulting in a failure due to missing privileges of the user. 
It was also triggered when unrelated files were modified.
This PR fixes that.

Only trigger pistache.io deploy when needed

---

meson.build
tools/format.sh

Since Meson doesn't have a way of specifying the working directory of a command, I had to modify the script to make it cd into the source root when ran from Meson.
You can run the format target with `meson compile -C builddir format` or `ninja -C builddir format`.
Also, I changed the shell from bash to `/bin/sh`, since bash isn't really required and a generic POSIX shell would work just fine

Add Meson clang-format target

---

README.md
src/meson.build

Previously it was stated that users needed to use `dependency('pistache')` to find the library through pkg-config, even though the .pc file is called `libpistache`. Don't know how I didn't noticed before :/

Fix pkg-config usage with Meson in Readme

---

include/pistache/prototype.h

I have [noticed](https://travis-ci.org/github/pistacheio/pistache/jobs/766565105#L3939) a warning message:
```
[104/169] Compiling C++ object tests/r...est_size_test.p/request_size_test.cc.o
In file included from ../include/pistache/tcp.h:14,
from ../include/pistache/http.h:29,
from ../include/pistache/client.h:10,
from ../tests/request_size_test.cc:2:
../include/pistache/prototype.h:26:50: warning: backslash-newline at end of file
#define PROTOTYPE_OF(Base, Class)                \
```

Fix warning: backslash-newline at end of file

---

.travis.yml
CMakeLists.txt

I find it very difficult to navigate Travis CI logs, since all the tests output gets printed. With this change `meson test` and `cmake --target test` will print test logs only when they fail, reducing eccessive noise.

Make Travis less verbose

---

.travis.yml

Previously Gooletest was built from source 4 times per build machine, so 48 times per commit

Travis cleanups: install `libgtest-dev`, remove unused apt sources

---

CMakeLists.txt
tests/CMakeLists.txt

Using imported targets instead of manually passing link and include flags is less error-prone and a good practice in general. Unfortunately different versions on CMake import targets with different names, so it is needed to check whether the new target name exists or not. This also ensures that all the correct flags are passed to compiler (previously `-pthread` wasn't passed to the tests, so linking errors could've happened. I think that everything worked fine because `pistache_static` provided the needed `Threads::Threads` dependency). 
I would've liked to also use the `CURL::libcurl` imported target, but it requires CMake 3.12 and would break CentOS 8 compatibility.
Edit: forgot to mention that I've also removed the `enable_testing()` call, since it is already done by `include(CTest)` …

Use GTest imported target in tests/CMakeLists.txt

---

.github/workflows/pistache.io.yaml
pistache.io/package.json
pistache.io/yarn.lock

I've updated the deploy action to only install yarn, as installing both npm and yarn wasn't necessary. I've also upgraded Docusaurus using `yarn upgrade @docusaurus/core@2.0.0-alpha.75 @docusaurus/preset-classic@2.0.0-alpha.75`, and pistache.io/yarn.lock was automatically updated too. I wouldn't let @dependabot automatically update those dependencies and let Docusaurus itself handle them; a nice solution would be set up an action that periodically checks and update Docusaurus.

Update Docusaurus version and deploy script

---

.travis.yml
meson.build
tools/format.sh

I've just found out that Meson automatically sets up a clang-format target when clang-format is found on the system, so there's no need to manually add that target.
It can be ran with `ninja clang-format`.
Details about this Meson feature can be found [here](https://mesonbuild.com/Code-formatting.html#clangformat)

Remove custom format target in Meson

---

include/pistache/http.h
src/common/http.cc
src/common/transport.cc
src/server/endpoint.cc
tests/http_server_test.cc
tests/tcp_client.h

Analyzing issue #842  I have found several serious (from my point of view) problems in Pistache code and I'm fixing them in this Pull Request.
1) The following code for removing idle peers does not work at all:
```
...
response.send(Http::Code::Request_Timeout).then([=](ssize_t) { removePeer(idlePeer); }, [=](std::exception_ptr) { removePeer(idlePeer); });
...
```
because `putOnWire` (`send` -> `sendImpl` -> `putOnWire`) returns `Async::Deferred`:
```
...
return Async::Promise<ssize_t>(
[=](Async::Deferred<ssize_t> /*deferred*/) mutable {
return;
});
...
```
and as a result `removePeer` is not called.
2) Headers and body timeouts do not work appropriately. For instance, if you just execute connect to server on client side without sending any request data you will get:
```
HTTP/1.1 408 …
```

Fix issue #842 and small refactoring

---

src/server/endpoint.cc
tests/CMakeLists.txt
tests/endpoint_initialization_test.cc

fixes an issue where maxRequestSize and maxResponseSize are not correctly set in the handler instance if Endpoint.init is called after Endpoint.setHandler. In this case maxRequestSize and maxResponseSize were both set to their default values (4096 for maxRequestSize and Int32.max for maxResponseSize) even if the values configured in the options instance were set to other values.

fix endpoint initialization

---

meson.build

If someone is building Pistache from source as a subproject they are not going to commit any changes from there, and setting up the pre-commit hook is pointless. It is now also optional (that is, if git is not installed the hook won't be set, but it won't cause the build to fail), since git is not strictly needed to build the library, and if you don't have git installed you are probably not going to commit.
Tested with `autopkgtest` :)

Set up commit hook only if master project and make it "optional"

---

include/pistache/listener.h
src/server/listener.cc

New connections can come from either IPv4 or IPv6 addresses. Hence, use
a sockaddress structure that can handle both.

listener: use sockaddr_storage for socket addrs

---

pistache.io/docs/asynchronous-http-programming.md
pistache.io/docs/headers.md
pistache.io/docs/http-handler.md
pistache.io/docs/quickstart.md
pistache.io/docs/rest-description.md
pistache.io/docs/routing.md

Otherwise Docusaurus can't see the document's title, see https://github.com/pistacheio/pistache/actions/runs/974573916

Move copyright notices down the title in docs

---

debian/rules

The option was added in Meson 0.55.0, but we target Meson 0.50

Remove --no-tests option when preparing tarballs

---

.github/workflows/autopkgtest.yaml

This CI workflow builds and tests every commit and PR using autopkgtest. It builds a Debian Testing image using `autopkgtest-build-qemu` (`autopkgtest-buildvm-ubuntu-cloud` was too slow), builds the source package and test is with `autopkgtest`.
I'm trying to set this up for multiple architectures (see https://github.com/Tachi107/pistache/tree/actions-autopkgtest), but for whatever reason Ubuntu's `autopkgtest-build-qemu` is unable to build images for foreign architectures, as it fails with `"E: Unable to locate package linux-image-arm64"`, while it should be downloading it from https://packages.debian.org/testing/linux-image-arm64. This works fine on my Debian machine.
If you know how to help please let me know.

Add autopkgtest GitHub Action

---

.github/workflows/autopkgtest.yaml
README.md
tests/meson.build

This took **a lot** of time, as `autopkgtest-build-qemu` has been able to build non-x86 for less than a release (version 5.17, unreleased), and it isn't meant to be (easily) used on Ubuntu (and unfortunately GH Actions only support Ubuntu).
This is extremely fragile; adding a CPU core breaks something, adding a MB of RAM breaks something, installing recommended packages breaks something... you get it. But it works. Beautiful, isn't it?
This currently tests amd64, arm64. armhf, i386 and ppc64el. s390x seems unsupported by `autopkgtest-build-qemu`.
If you're curious to see how many trials it took, have a look at this test branch: [Tachi107/pistache/tree/actions-autopkgtest-multiarch-test](https://github.com/Tachi107/pistache/tree/actions-autopkgtest-multiarch-test)

Add support for multiple archs in autopkgtest CI

---

.github/workflows/autopkgtest.yaml

autopkgtest is flaky and sometimes fails even if the code is completely fine. When it crashes like this, it exits with code 16.
With this change all CI runs that exit with code 16 won't be considered failures, but will just report a warning.
For more info, see `man autopkgtest`

autopkgtest: don't fail on testbed failures

---

include/pistache/typeid.h

Include `stddef.h` to avoid the following build failure with gcc 11:
```
In file included from /tmp/instance-3/output-1/build/pistache-f2f5a50fbfb5b8ef6cf1d3d2a9d442a8270e375d/src/../include/pistache/async.h:10,
from /tmp/instance-3/output-1/build/pistache-f2f5a50fbfb5b8ef6cf1d3d2a9d442a8270e375d/src/../include/pistache/client.h:9,
from /tmp/instance-3/output-1/build/pistache-f2f5a50fbfb5b8ef6cf1d3d2a9d442a8270e375d/src/client/client.cc:7:
/tmp/instance-3/output-1/build/pistache-f2f5a50fbfb5b8ef6cf1d3d2a9d442a8270e375d/src/../include/pistache/typeid.h:26:12: error: expected type-specifier before 'size_t'
26 |   operator size_t() const { return reinterpret_cast<size_t>(id_); }
|            ^~~~~~
```
Fixes:
- http://autobuild.buildroot.org/results/2443559df8c2357476e4cbdbebb08280cbb80a3b …

include/pistache/typeid.h: include stddef.h

---

meson.build

On some operating systems (like Raspberry Pi OS) with libatomic installed meson configuration succeeds when it shouldn't. Actually building fails on the linking phase because of missing methods in 32 bit version of libatomic.
Improved meson checks added to avoid confusion (and false hope).

also check for linking with libatomic

---

include/pistache/endpoint.h
include/pistache/listener.h
src/server/endpoint.cc
src/server/listener.cc

In order to use passphrase-protected keys.
This patch does not change the default behavior:
server.useSSL("./cert/server.crt", "./cert/server.key");
$> ./a.out
Enter PEM pass phrase:
[...]
static int password_callback(char *buf, int size, int rwflag, void *u)
{
static const char *password = "foobar"; // _Please_ don't do that, that's an example
strncpy(buf, password, size);
return strlen(password);
}
server.useSSL("./cert/server.crt", "./cert/server.key", false, &password_callback);
$> ./a.out
Listening on 0.0.0.0:9080
Key has been generated with:
$> openssl genrsa -aes128 -passout pass:foobar -out server.key 3072
If you intend to use this feature, please look at the recent
developments on memfd_secret[1] in order to actually store a passphrase
with relative security in memory.
[1] …

[SERVER] ssl: Add the possibility for the user to set a password callback

---

.github/workflows/conventional-commits.yaml

[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) is a specification that aims at improving commit messages and history.
It consists of a simple canonical format for commit messages: `type(optional scope): description`
Having a small list of types helps understand when a change is breaking, when it adds a feature, where it patches something, or when it is unrelated to the main library (build system changes, CI, tests...).
This is really useful when determining when to release and what type of release should be made (major, minor, or patch release).
Getting used to it takes a while, but its benefits are real

ci: add conventional commits check

---

control

The Meson Debian package should depend on that package itself, but for some reason it doesn't (for details, see https://github.com/mesonbuild/meson/issues/4267#issuecomment-920919273)

build(debian): depend on python3-distutils

---

meson.build

Since the "date" library has such a general name, it often gets renamed to "hinnant-date", "howardhinnant-date", etc. This change enables Meson to find the library when it is called in either ways. This "new" name is used, for example, in the Debian package.

build(meson): look for howardhinnant-date

---

changelog
control
libpistache-dev.docs
libpistache0.docs
rules
watch

This allows the use of uscan to get the upstream source, a much more elegant approach.
See https://manpages.debian.org/uscan.1.html#direct_access_to_the_git_repository_(HEAD)
I've also fixed a few Lintian warnings, like including the license with the docs, using the wrong section for the package, not including the ITP bug in the first changelog entry and wrong capitalization of Vcs-Browser. The only major violation left is the use of the "libpistache0" package name even if the SONAME is 0.0. I would suggest removing the minor SOVERSION, as ABI is either compatible or incompatible, there's no "minor" incompatibility. More of this in a separate PR.
This should not be merged yet, as I have to update the autopkgtest CI job.

build(debian): use d/watch to download latest HEAD

---

src/server/listener.cc

This patch enables the partial write mode on the SSL server context,
giving us "normal" behavior on non-blocking sockets.
This patch is meant to be a sleep-less alternative to https://github.com/pistacheio/pistache/pull/832,
with the advantage of also fixing a potential issue on file streaming.
Should not break any behavior.
Signed-off-by: Louis Solofrizzo <lsolofrizzo@scaleway.com>

ssl: Enable partial write on SSL context

---

.github/workflows/abipkgdiff.yaml

`abipkgdiff` is a tool capable of comparing two library packages and tell if one of them introduced ABI-breaking changes.
Plain `abidiff` is also available, but since we already build Debian packages I thought it would be more convenient to use pkg version.

ci: add abipkgdiff check

---

src/server/listener.cc

Due to internals of pistache, a write after a retry may be with a
different address than the original call. By default, OpenSSL doesn't
like that:
SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER
Make it possible to retry SSL_write() with changed buffer location
(the buffer contents must stay the same). This is not the default to
avoid the misconception that non-blocking SSL_write() behaves like
non-blocking write().
This should fix any weird behavior on large file / responses (#807)
Signed-off-by: Louis Solofrizzo <lsolofrizzo@scaleway.com>

fix(ssl): enable ssl mode for moving buffers

---

watch

This was needed to replace the default `~git$date.$hash` suffix with `+git$date.$hash`, because in Debian `+` is greater than `~`, and it was needed to make the PPA happy. This unfortunately requires the d/watch file to be updated every time the version number is bumped.
Dropping the custom version in d/watch and relying on the default is just better, and will also fix CI.
This must be merged **before** #1010, and if this gets merged #1010 must be merged as well

d/watch: remove manual `pretty` option

---

watch

I tried dropping it in cec95bc171675c908ae1140ee1277e44a42109df, but unfortunately until we tag a release we'll have to manually update the watch file.
I'm not sure this will completely fix all CI issues, but merging this would help me debugging it anyway

watch: use manual pretty option

---

.github/workflows/autopkgtest.yaml

Building it from source is not needed anymore

ci(autopkgtest): install autopkgtest from Debian Testing

---

src/common/transport.cc

I'm also currently facing the issue described in #1007. I added the MSG_NOSIGNAL Flag as proposed by @amang8662. But there was still the problem, how to get the info if the socket is still alive. So I checked on the documentation (https://linux.die.net/man/3/getsockopt). With the function `getsockopt()` you are able to receive the last error of the socket. In case the pipe breaks, the error is returned through this function. So we can check if the stream is still alive by testing the return value. 
I added the function `isOpen()` which returns true if there isn't an error on the socket and false otherwise.
This is my first PR in any open-source project. So I hope for leniency.

Possible solution for BUG#1007

---

.github/workflows/autopkgtest.yaml

A Debian package version is usually composed like this: `upstream_version+suffix-revision`
The .orig tarball needs to only have the upstream_version part plus the suffix, so I previously used `cut -d - -f 1` to split the Debian version at the first hyphen and obtain the upstream version.
This works in our case, because:
$ echo 0.0.003-1 | cut -d - -f 1
0.0.003
but it is perfectly legal to have an upstream version containing hyphens itself:
$ echo 0.0.4-beta-1 | cut -d - -f 1
0.0.4
and this results in a wrong upstream version, as -beta is cut out.
A way to avoid this is to use awk instead of cut. I originally preferred cut as it is a simpler tool and I don't know awk at all, but unfortunately it is too simple.
Hyphens in the upstream version are now handled correctly:
$ echo 0.0.4-beta-1 | …

ci(autopkgtest): use awk to get the upstream version

---

CNAME

This should make it possible to reach the Pistache website at [pistacheio.github.io/pistache](https://pistacheio.github.io/pistache)

Remove CNAME file from gh-pages

---

.github/workflows/autopkgtest.yaml
.github/workflows/linux.yaml
.hooks/pre-commit
README.md

This new CI job builds and tests Pistache on different Linux distros, with different compilers, and under different sanitizers, and also re-adds Codecov coverage integration back.
Currently, Pistache is tested on Debian Stable, Debian Testing and Red Hat Enterprise Linux 8, and the code is built with GCC and Clang. Sanitizers are only used on Debian, because as far as I'm aware RHEL doesn't ship the various sanitizers in its base images.
ThreadSanitizer is also disabled for now, as it reports a lot of data races in some tests. Some of the bugs are in the unit tests themselves, but I haven't yet looked into solving them. @dennisjenkins75 I seem to remember that you opened a meta-issue about dace conditions in Pistache but I haven't found it.
~I'll add RHEL 9 as soon as Red Hat publishes …

ci: build on multiple Linux distributions

---

.github/workflows/linux.yaml

This allows us to test that Pistache links and works correctly with LLVM's LLD linker, and also fixes the issues with the RHEL 8 / Clang job

ci(linux): use LLD when using Clang

---

CMakeLists.txt
src/CMakeLists.txt

In this PR I've made some minor improvements to the CMake files so that Pistache plays more nicely when it is included as a subproject. See the individual commits for details.

CMake subproject fixes

---

.github/workflows/autopkgtest.yaml

So that contributors don't have to keep in sync both the `master` and `debian` branches.

ci(autopkgtest): get debian/ from pistacheio/pistache

---

.github/workflows/linux.yaml
tests/listener_tls_test.cc
tests/meson.build

The new `tls_handshake_timeout` test is source-compatible with Pistache versions with and without the fix in #1115, so that it is easy to test if the bug reproduces with and without that patch applied.

test: listener TLS handshake timeout test

---

.github/workflows/debian-changelog.yaml

This CI job will run when `version.txt` is updated in the `master` branch, and will push a new commit to the `debian` branch updating the changelog.
`DEBFULLNAME` and `DEBEMAIL` are set by "parsing" the control file. If you know a true debian/control parser that could be used instead, preferably part of dpkg or devscripts, please let me know.
This script currently only updates the single existing changelog entry. It could be possible to make it add a new entry each time instead, but it'd be a bit more involved and we would have to first check if it'd be compatible with our current PPA setup, which I personally don't know very well.
Closes #1119

ci: automatically update debian/changelog

---

src/server/listener.cc

Fix the following libressl build failure:
```
../src/server/listener.cc: In member function 'void Pistache::Tcp::Listener::setupSSLAuth(const std::string&, const std::string&, int (*)(int, void*))': ../src/server/listener.cc:582:29: error: 'SSL_verify_cb' was not declared in this scope; did you mean 'RSA_verify'?
582 |                            (SSL_verify_cb)cb
|                             ^~~~~~~~~~~~~
|                             RSA_verify
```
Fixes:
- http://autobuild.buildroot.org/results/066fc078980e5216f38411eee455088e15fa1101

src/server/listener.cc: fix libressl build

---

README.md

Pistache is now packaged in Debian, and will soon be in Ubuntu too (it is already part of the development snapshot of Ubuntu 23.10)

docs: update Debian packaging status

---

tests/net_test.cc

The test case "address_creation" relies on resolving the name www.example.com to succeed. It means that testing the project on environments without access to a DNS server will fail. Use the name "localhost" instead so the local resolver will not need to query a DNS server.

tests/net_test: don't try to resolve external names

---

tests/headers_test.cc
tests/http_client_test.cc
tests/view_test.cc

Using `EXPECT_EQ(var1, var2)` instead of `EXPECT_TRUE(var1 == var2)` offers more helpful error messages in case of test failures. The same goes for `EXPECT_STREQ("str1", "str2")` vs `EXPECT_EQ(strcmp("str1", "str2"), 0)`.

test: more precise GTest assertions

---

.github/workflows/linux.yaml

This increases test coverage, since both compressed and uncompressed requests are made by the test suite.

ci(linux): enable compression

---

src/meson.build

Public arguments are now specifically added to the libpistache and pistache_dep objects, so that they automatically get propagated to all the build targets which depend on pistache_dep.
Follow-up to 575ccf415232dfbafb827b0fcde68f6657e8f7dd

build: better handle public compile arguments

---

control

This is needed for pkg-config to work properly, since it requires that .pc files are installed even for Requires.private dependencies.
Should fix the issues described in <https://github.com/pistacheio/pistache/issues/1185#issuecomment-1887916403>

control: make -dev package depend on libbrotli-dev

---

.github/workflows/linux.yaml

This is a temporary workaround to the Coverage failures on Debian Testing.

ci(linux): only run Coverage step on Debian Stable

---

tests/cookie_test.cc

Citing @dgreatwood:
the line that goes wrong in cookie_test.cc is this:
FullDate::time_point expires = date::sys_days(date::year { 118 } / 2 / 16) + hours(17);
The first puzzle (to me!) is what  "year { 118 }" means. Per:
https://en.cppreference.com/w/cpp/chrono/year/year
> This is constructing an instance of std::chrono::year with value 118. Per:
https://en.cppreference.com/w/cpp/chrono/year_month_day/operator_days
The "118" is a value in the "proleptic Gregorian calendar", i.e. it means the year 118 A.D.
Then sys_days is an operator that converts std::chrono::year_month_day to a std::chrono::time_point
https://en.cppreference.com/w/cpp/chrono/year_month_day/operator_days
Also note that:
> 1) If ok() is true, the return value holds a count of days from the std::chrono::system_clock epoch …

test: fix integer overflow in cookie_test

---

control

In lockstep with #1218 for #1126

control: require meson 0.53.2+

---

meson.build

Some tools, such as Buildroot, will use packed tarballs of cloned git repositories and trigger builds for the sources.
Currently, pistache will install githooks via `git config --local` for any build, even if it's not done from a git checkout. Since the source/build directory is not an actual git checkout, the command traverses up the directory hierarchy and will corrupt the git config for the Buildroot checkout.
```
Buildroot/
.git/config  # <- this gets corrupted
output/
build/
unpacked-pistache-@-commit-hash-without-.git-directory/
```
Now, we check that the source root directory has a `.git` directory before attempting to install githooks.
Fixes #1126

Only install githooks for local checkouts

---

src/common/http_defs.cc

The `put_time()` function formats dates according to `strftime()`. Its `Z` conversion specifier, according to cppreference, doesn't print the time zone name of the `std::tm` pointer passed to `strftime()`, but instead the time zone name associated with the current locale; citing the [`strftime()`
documentation](https://en.cppreference.com/w/cpp/chrono/c/strftime):
> |  Conversion specifier | Explanation | Used fields |
> | --- | --- | --- |
> | Z | writes locale-dependent time zone name or abbreviation, or no characters if the time zone information is not available | tm_isdst |
In fact, according to the C++ standard, `strftime()` can never print the time zone information associated with a an `std::tm` object, because it doesn't even have a struct member representing it!
But still, you've …

fix: avoid using %Z format specifier with gmtime()

---

meson.build
src/meson.build

Since a RapidJSON header is included in
include/pistache/serializer/rapidjson.h, users using pistache must also add RapidJSON to their include path. Adding rapidjson_dep to the list of dependencies of pistache_dep makes rapidjson_dep a transitive (public) dependency, doing just that.
Should fix the issue encountered by Duncan in
<https://github.com/pistacheio/pistache/pull/1221/files#r1693921738>. Also closes https://github.com/pistacheio/pistache/pull/1224

build: make rapidjson_dep a public dependency

---

meson.build
src/meson.build

Since Pistache includes various headers from third party dependencies in its own public headers, it is necessary to mark the respective dependencies as public, so that consumers of the libpistache dependency will know that in addition to the include path of Pistache, they'll also have to look for OpenSSL headers, zlib headers, etc.
Should fix an issue reported by Duncan via email.

build: properly handle public dependencies

---

README.md
src/CMakeLists.txt
src/meson.build

Until the 1.0 release, setting the soname to `version_major.version_minor` gives us more freedom to make changes without being too restricted by ABI compatibility.
We never actually really commited to ABI stability before the 1.0 relase - the README states that at the bottom - but I made this decision clearer by updating the "versioning" section.

build: set soname to major.minor

---

changelog
control
rules

Following #1247 and #1200
Adds libzstd-dev to build dependencies

Add zstd compression support to package build dependencies

---

src/common/pist_timelog.cc

Avoid static initialization order fiasco in case an application itself uses statics which depend on the library.
Solved by using a getter if local static which is guaranteed to be initialized on first call to function.

Avoid SIOF with lazy init

---

meson.build

Delete erroneous comment claiming that compiler.has_function is broken. This is based on a misunderstanding of the original logfile. See: https://github.com/pistacheio/pistache/pull/1252#discussion_r1924598159
Checking for dladdr works fine. Checking for `dependency('dl')` on versions of meson that are too old to support it does not work, and this is what happened on RedHat ubi-8.
/cc @dgreatwood

meson: check for availability of dladdr

---

src/common/http_defs.cc

The Date header sometimes is an epoch (e.g. git)
Handle such cases instead of dropping the request.
Tested locally, works fine.

Fix: Date header parsing when date is an epoch
